// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"go-zero-dandan/common/dao"
	"go-zero-dandan/common/redisd"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	userInfoFieldNames          = builder.RawFieldNames(&UserInfo{})
	userInfoRows                = strings.Join(userInfoFieldNames, ",")
	userInfoRowsExpectAutoSet   = strings.Join(stringx.Remove(userInfoFieldNames, "`delete_at`"), ",")
	userInfoRowsWithPlaceHolder = strings.Join(stringx.Remove(userInfoFieldNames, "`id`", "`delete_at`"), "=?,") + "=?"
)

type (
	userInfoModel interface {
		Insert(data map[string]string) (int64, error)
		TxInsert(tx *sql.Tx, data map[string]string) (int64, error)
		FindOne(id int64) (*UserInfo, error)
		Update(data map[string]string) (affectRows int64, err error)
		Save(data map[string]string) (int64, error)
		Delete(id ...int64) (int64, error)
		Field(field string) *defaultUserInfoModel
		Alias(alias string) *defaultUserInfoModel
		WhereStr(whereStr string) *defaultUserInfoModel
		WhereId(id int) *defaultUserInfoModel
		WhereRaw(whereStr string, whereData []any) *defaultUserInfoModel
		Order(order string) *defaultUserInfoModel
		Plat(id int) *defaultUserInfoModel
		Find(id ...any) (*UserInfo, error)
		CacheFind(redis *redisd.Redisd, id ...int64) (*UserInfo, error)
		Page(page int, rows int) ([]*UserInfo, error)
		List() ([]*UserInfo, error)
		Count() (int, error)
		Inc(field string, num int) (int64, error)
		Dec(field string, num int) (int64, error)
		Ctx(ctx context.Context) *defaultUserInfoModel
	}

	defaultUserInfoModel struct {
		conn            sqlx.SqlConn
		dao             *dao.SqlxDao
		table           string
		softDeleteField string
		softDeletable   bool
		fieldSql        string
		whereSql        string
		aliasSql        string
		orderSql        string
		platId          int64
		whereData       []any
		err             error
		ctx             context.Context
	}

	UserInfo struct {
		Id           int64     `db:"id"`
		BirthDate    time.Time `db:"birth_date"`    // 出生日期
		GraduateFrom string    `db:"graduate_from"` // 毕业学校
		PlatId       int64     `db:"plat_id"`       // 应用id
		CreateAt     int64     `db:"create_at"`     // 创建时间戳
		UpdateAt     int64     `db:"update_at"`     // 更新时间戳
		DeleteAt     int64     `db:"delete_at"`     // 删除时间戳
	}
)

func newUserInfoModel(conn sqlx.SqlConn, platId int64) *defaultUserInfoModel {
	dao := dao.NewSqlxDao(conn, "`user_info`", userInfoRows, false, "delete_at")
	return &defaultUserInfoModel{
		conn:            conn,
		dao:             dao,
		table:           "`user_info`",
		softDeleteField: "delete_at",
		whereData:       make([]any, 0),
		platId:          platId,
	}
}
func (m *defaultUserInfoModel) Ctx(ctx context.Context) *defaultUserInfoModel {
	m.dao.Ctx(ctx)
	return m
}
func (m *defaultUserInfoModel) WhereId(id int) *defaultUserInfoModel {
	m.dao.WhereId(id)
	return m
}

func (m *defaultUserInfoModel) WhereStr(whereStr string) *defaultUserInfoModel {
	m.dao.WhereStr(whereStr)
	return m
}

func (m *defaultUserInfoModel) WhereRaw(whereStr string, whereData []any) *defaultUserInfoModel {
	m.dao.WhereRaw(whereStr, whereData)
	return m
}
func (m *defaultUserInfoModel) Alias(alias string) *defaultUserInfoModel {
	m.dao.Alias(alias)
	return m
}
func (m *defaultUserInfoModel) Field(field string) *defaultUserInfoModel {
	m.dao.Field(field)
	return m
}
func (m *defaultUserInfoModel) Order(order string) *defaultUserInfoModel {
	m.dao.Order(order)
	return m
}
func (m *defaultUserInfoModel) Count() (int, error) {
	return m.dao.Count()
}
func (m *defaultUserInfoModel) Inc(field string, num int) (int64, error) {
	return m.dao.Inc(field, num)
}
func (m *defaultUserInfoModel) TxInc(tx *sql.Tx, field string, num int) (int64, error) {
	return m.dao.TxInc(tx, field, num)
}
func (m *defaultUserInfoModel) Dec(field string, num int) (int64, error) {
	return m.dao.Dec(field, num)
}
func (m *defaultUserInfoModel) TxDec(tx *sql.Tx, field string, num int) (int64, error) {
	return m.dao.TxDec(tx, field, num)
}
func (m *defaultUserInfoModel) Plat(id int) *defaultUserInfoModel {

	return nil
}
func (m *defaultUserInfoModel) CacheFind(redis *redisd.Redisd, id ...int64) (*UserInfo, error) {
	resp := &UserInfo{}
	err := m.dao.CacheFind(redis, resp, id...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *defaultUserInfoModel) Delete(id ...int64) (int64, error) {
	return m.dao.Delete(id...)
}
func (m *defaultUserInfoModel) TxDelete(tx *sql.Tx, id ...int64) (int64, error) {
	return m.dao.TxDelete(tx, id...)
}
func (m *defaultUserInfoModel) Find(id ...any) (*UserInfo, error) {
	resp := &UserInfo{}
	err := m.dao.Find(resp, id...)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
func (m *defaultUserInfoModel) List() ([]*UserInfo, error) {
	resp := make([]*UserInfo, 0)
	return resp, nil
}
func (m *defaultUserInfoModel) Page(page int, rows int) ([]*UserInfo, error) {
	resp := make([]*UserInfo, 0)
	return resp, nil
}
func (m *defaultUserInfoModel) FindOne(id int64) (*UserInfo, error) {
	resp := &UserInfo{}
	return resp, nil
}
func (m *defaultUserInfoModel) Reinit() {
	m.dao.Reinit()
}

func (m *defaultUserInfoModel) Insert(data map[string]string) (int64, error) {
	return 0, nil
}
func (m *defaultUserInfoModel) TxInsert(tx *sql.Tx, data map[string]string) (int64, error) {

	return 0, nil
}
func (m *defaultUserInfoModel) Update(data map[string]string) (int64, error) {
	return m.dao.Update(data)
}
func (m *defaultUserInfoModel) Save(data map[string]string) (int64, error) {
	return m.dao.Save(data)
}

func (m *defaultUserInfoModel) tableName() string {
	return m.table
}
