[jwt]
expireDuration = "12h"
secret = "i1ydX9RtHyuJTrw7frcu"
type = "refresh_token"
refreshDuration = "168h"

[mysql]
[mysql.base]
connMaxLifeTime = "3m"
maxIdleConn = 30
maxOpenConn = 60
addr = "mysql:3306"
name = "sail"
pass = "8a7yNLrsThjw3jra"
user = "root"

[etcd]
endpoints = ["http://etcd:2379"]
username = ""
password = ""
dialTimeout = "10s"
dialKeepAlive = "1m"
dialKeepAliveTimeout = "5s"

[log]
logPath = "./services.log"
level = "DEBUG" # DEBUG INFO WARN ERROR
stdout = true
jsonFormat = true

[server]
serverName = "sail"
host = ":8108"
pprof = true
historyListLen = 50

[sdk]
configFilePath = "."
logLevel = "WARN"
MergeConfig = false