// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.29.0
// 	protoc        v3.19.4
// source: plat.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IdReq struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *IdReq) Reset() {
	*x = IdReq{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plat_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *IdReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdReq) ProtoMessage() {}

func (x *IdReq) ProtoReflect() protoreflect.Message {
	mi := &file_plat_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdReq.ProtoReflect.Descriptor instead.
func (*IdReq) Descriptor() ([]byte, []int) {
	return file_plat_proto_rawDescGZIP(), []int{0}
}

func (x *IdReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type PlatInfo struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id     int64 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClasEm int64 `protobuf:"varint,2,opt,name=ClasEm,proto3" json:"ClasEm,omitempty"`
}

func (x *PlatInfo) Reset() {
	*x = PlatInfo{}
	if protoimpl.UnsafeEnabled {
		mi := &file_plat_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *PlatInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PlatInfo) ProtoMessage() {}

func (x *PlatInfo) ProtoReflect() protoreflect.Message {
	mi := &file_plat_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PlatInfo.ProtoReflect.Descriptor instead.
func (*PlatInfo) Descriptor() ([]byte, []int) {
	return file_plat_proto_rawDescGZIP(), []int{1}
}

func (x *PlatInfo) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *PlatInfo) GetClasEm() int64 {
	if x != nil {
		return x.ClasEm
	}
	return 0
}

var File_plat_proto protoreflect.FileDescriptor

var file_plat_proto_rawDesc = []byte{
	0x0a, 0x0a, 0x70, 0x6c, 0x61, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x04, 0x70, 0x6c,
	0x61, 0x74, 0x22, 0x17, 0x0a, 0x05, 0x49, 0x64, 0x52, 0x65, 0x71, 0x12, 0x0e, 0x0a, 0x02, 0x69,
	0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x22, 0x32, 0x0a, 0x08, 0x50,
	0x6c, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01, 0x20,
	0x01, 0x28, 0x03, 0x52, 0x02, 0x69, 0x64, 0x12, 0x16, 0x0a, 0x06, 0x43, 0x6c, 0x61, 0x73, 0x45,
	0x6d, 0x18, 0x02, 0x20, 0x01, 0x28, 0x03, 0x52, 0x06, 0x43, 0x6c, 0x61, 0x73, 0x45, 0x6d, 0x32,
	0x2d, 0x0a, 0x04, 0x70, 0x6c, 0x61, 0x74, 0x12, 0x25, 0x0a, 0x06, 0x47, 0x65, 0x74, 0x4f, 0x6e,
	0x65, 0x12, 0x0b, 0x2e, 0x70, 0x6c, 0x61, 0x74, 0x2e, 0x49, 0x64, 0x52, 0x65, 0x71, 0x1a, 0x0e,
	0x2e, 0x70, 0x6c, 0x61, 0x74, 0x2e, 0x50, 0x6c, 0x61, 0x74, 0x49, 0x6e, 0x66, 0x6f, 0x42, 0x06,
	0x5a, 0x04, 0x2e, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_plat_proto_rawDescOnce sync.Once
	file_plat_proto_rawDescData = file_plat_proto_rawDesc
)

func file_plat_proto_rawDescGZIP() []byte {
	file_plat_proto_rawDescOnce.Do(func() {
		file_plat_proto_rawDescData = protoimpl.X.CompressGZIP(file_plat_proto_rawDescData)
	})
	return file_plat_proto_rawDescData
}

var file_plat_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_plat_proto_goTypes = []interface{}{
	(*IdReq)(nil),    // 0: plat.IdReq
	(*PlatInfo)(nil), // 1: plat.PlatInfo
}
var file_plat_proto_depIdxs = []int32{
	0, // 0: plat.plat.GetOne:input_type -> plat.IdReq
	1, // 1: plat.plat.GetOne:output_type -> plat.PlatInfo
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_plat_proto_init() }
func file_plat_proto_init() {
	if File_plat_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_plat_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*IdReq); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_plat_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*PlatInfo); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_plat_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_plat_proto_goTypes,
		DependencyIndexes: file_plat_proto_depIdxs,
		MessageInfos:      file_plat_proto_msgTypes,
	}.Build()
	File_plat_proto = out.File
	file_plat_proto_rawDesc = nil
	file_plat_proto_goTypes = nil
	file_plat_proto_depIdxs = nil
}
