// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	user "go-zero-dandan/app/user/api/internal/handler/user"
	"go-zero-dandan/app/user/api/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		rest.WithMiddlewares(
			[]rest.Middleware{serverCtx.LangMiddleware},
			[]rest.Route{
				{
					Method:  http.MethodPost,
					Path:    "/regByPhone",
					Handler: user.RegByPhoneHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/loginByPhone",
					Handler: user.LoginByPhoneHandler(serverCtx),
				},
				{
					Method:  http.MethodPost,
					Path:    "/getPhoneVerifyCode",
					Handler: user.GetPhoneVerifyCodeHandler(serverCtx),
				},
			}...,
		),
		rest.WithJwt(serverCtx.Config.Auth.AccessSecret),
		rest.WithPrefix("/user/v1"),
	)
}
