// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package server

import (
	"context"

	"go-zero-dandan/app/message/rpc/internal/logic"
	"go-zero-dandan/app/message/rpc/internal/svc"
	"go-zero-dandan/app/message/rpc/types/pb"
)

type MessageServer struct {
	svcCtx *svc.ServiceContext
	pb.UnimplementedMessageServer
}

func NewMessageServer(svcCtx *svc.ServiceContext) *MessageServer {
	return &MessageServer{
		svcCtx: svcCtx,
	}
}

func (s *MessageServer) SendPhone(ctx context.Context, in *pb.SendPhoneReq) (*pb.SuccResp, error) {
	l := logic.NewSendPhoneLogic(ctx, s.svcCtx)
	return l.SendPhone(in)
}

func (s *MessageServer) SendSMSAsync(ctx context.Context, in *pb.SendPhoneReq) (*pb.SuccResp, error) {
	l := logic.NewSendSMSAsyncLogic(ctx, s.svcCtx)
	return l.SendSMSAsync(in)
}
