// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"go-zero-dandan/common/dao"
	"go-zero-dandan/common/redisd"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	platMainFieldNames          = builder.RawFieldNames(&PlatMain{})
	platMainRows                = strings.Join(platMainFieldNames, ",")
	defaultPlatMainFields       = strings.Join(platMainFieldNames, ",")
	platMainRowsExpectAutoSet   = strings.Join(stringx.Remove(platMainFieldNames, "`delete_at`"), ",")
	platMainRowsWithPlaceHolder = strings.Join(stringx.Remove(platMainFieldNames, "`id`", "`delete_at`"), "=?,") + "=?"
)

type (
	platMainModel interface {
		Insert(data *PlatMain) (int64, error)
		TxInsert(tx *sql.Tx, data *PlatMain) (int64, error)
		Update(data map[string]any) (int64, error)
		TxUpdate(tx *sql.Tx, data map[string]any) (int64, error)
		Save(data *PlatMain) (int64, error)
		TxSave(tx *sql.Tx, data *PlatMain) (int64, error)
		Delete(ctx context.Context, id int64) error
		Field(field string) *defaultPlatMainModel
		Alias(alias string) *defaultPlatMainModel
		Where(whereStr string, whereData ...any) *defaultPlatMainModel
		WhereId(id int64) *defaultPlatMainModel
		Order(order string) *defaultPlatMainModel
		Limit(num int64) *defaultPlatMainModel
		Plat(id int64) *defaultPlatMainModel
		Find() (*PlatMain, error)
		FindById(id int64) (*PlatMain, error)
		CacheFind(redis *redisd.Redisd) (*PlatMain, error)
		CacheFindById(redis *redisd.Redisd, id int64) (*PlatMain, error)
		Page(page int64, rows int64) *defaultPlatMainModel
		Select() ([]*PlatMain, error)
		SelectWithTotal() ([]*PlatMain, int64, error)
		CacheSelect(redis *redisd.Redisd) ([]*PlatMain, error)
		Count() (int64, error)
		Inc(field string, num int) (int64, error)
		Dec(field string, num int) (int64, error)
		Ctx(ctx context.Context) *defaultPlatMainModel
		Reinit() *defaultPlatMainModel
		Dao() *dao.SqlxDao
	}

	defaultPlatMainModel struct {
		conn            sqlx.SqlConn
		table           string
		dao             *dao.SqlxDao
		softDeleteField string
		softDeletable   bool
		fieldSql        string
		whereSql        string
		aliasSql        string
		orderSql        string
		platId          int64
		whereData       []any
		err             error
		ctx             context.Context
	}

	PlatMain struct {
		Id          int64  `db:"id"`
		Appid       string `db:"appid"`         // 对外应用标识
		Secret      string `db:"secret"`        // 对外应用密钥
		StateEm     int64  `db:"state_em"`      // 应用状态
		RenterId    int64  `db:"renter_id"`     // 租户id
		Name        string `db:"name"`          // 应用名称
		ClasEm      int64  `db:"clas_em"`       // 应用类型
		ExpireAt    int64  `db:"expire_at"`     // 应用到期时间戳
		DataLevelEm int64  `db:"data_level_em"` // 应用数据隔离级别，0单应用级，1同用户所有应用，99不隔离平台应用
		CreateAt    int64  `db:"create_at"`     // 创建时间戳
		UpdateAt    int64  `db:"update_at"`     // 更新时间戳
		DeleteAt    int64  `db:"delete_at"`     // 删除时间戳
	}
)

func newPlatMainModel(conn sqlx.SqlConn, platId int64) *defaultPlatMainModel {
	dao := dao.NewSqlxDao(conn, "`plat_main`", defaultPlatMainFields, true, "delete_at")
	dao.Plat(platId)
	return &defaultPlatMainModel{
		conn:            conn,
		dao:             dao,
		table:           "`plat_main`",
		platId:          platId,
		softDeleteField: "delete_at",
		whereData:       make([]any, 0),
	}
}
func (m *defaultPlatMainModel) Ctx(ctx context.Context) *defaultPlatMainModel {
	m.dao.Ctx(ctx)
	return m
}
func (m *defaultPlatMainModel) WhereId(id int64) *defaultPlatMainModel {
	m.dao.WhereId(id)
	return m
}

func (m *defaultPlatMainModel) Where(whereStr string, whereData ...any) *defaultPlatMainModel {
	m.dao.Where(whereStr, whereData...)
	return m
}

func (m *defaultPlatMainModel) Alias(alias string) *defaultPlatMainModel {
	m.dao.Alias(alias)
	return m
}
func (m *defaultPlatMainModel) Field(field string) *defaultPlatMainModel {
	m.dao.Field(field)
	return m
}
func (m *defaultPlatMainModel) Order(order string) *defaultPlatMainModel {
	m.dao.Order(order)
	return m
}
func (m *defaultPlatMainModel) Limit(num int64) *defaultPlatMainModel {
	m.dao.Limit(num)
	return m
}
func (m *defaultPlatMainModel) Count() (int64, error) {
	return m.dao.Count()
}
func (m *defaultPlatMainModel) Inc(field string, num int) (int64, error) {
	return m.dao.Inc(field, num)
}
func (m *defaultPlatMainModel) TxInc(tx *sql.Tx, field string, num int) (int64, error) {
	return m.dao.TxInc(tx, field, num)
}
func (m *defaultPlatMainModel) Dec(field string, num int) (int64, error) {
	return m.dao.Dec(field, num)
}
func (m *defaultPlatMainModel) TxDec(tx *sql.Tx, field string, num int) (int64, error) {
	return m.dao.Dec(field, num)
}
func (m *defaultPlatMainModel) Plat(id int64) *defaultPlatMainModel {
	m.dao.Plat(id)
	return m
}
func (m *defaultPlatMainModel) Reinit() *defaultPlatMainModel {
	m.dao.Reinit()
	return m
}
func (m *defaultPlatMainModel) Dao() *dao.SqlxDao {
	return m.dao
}
func (m *defaultPlatMainModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultPlatMainModel) Find() (*PlatMain, error) {
	resp := &PlatMain{}
	err := m.dao.Find(resp)
	if err != nil {
		if err == sqlx.ErrNotFound {
			return nil, nil
		}
		return nil, err
	}
	return resp, nil
}
func (m *defaultPlatMainModel) FindById(id int64) (*PlatMain, error) {
	resp := &PlatMain{}
	err := m.dao.FindById(resp, id)
	if err != nil {
		if err == sqlx.ErrNotFound {
			return nil, nil
		}
		return nil, err
	}
	return resp, nil
}
func (m *defaultPlatMainModel) CacheFind(redis *redisd.Redisd) (*PlatMain, error) {
	resp := &PlatMain{}
	err := m.dao.CacheFind(redis, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
func (m *defaultPlatMainModel) CacheFindById(redis *redisd.Redisd, id int64) (*PlatMain, error) {
	resp := &PlatMain{}
	err := m.dao.CacheFindById(redis, resp, id)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *defaultPlatMainModel) Select() ([]*PlatMain, error) {
	resp := make([]*PlatMain, 0)
	err := m.dao.Select(&resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
func (m *defaultPlatMainModel) SelectWithTotal() ([]*PlatMain, int64, error) {
	resp := make([]*PlatMain, 0)
	var total int64
	err := m.dao.Select(&resp, &total)
	if err != nil {
		return nil, 0, err
	}
	return resp, total, nil
}
func (m *defaultPlatMainModel) CacheSelect(redis *redisd.Redisd) ([]*PlatMain, error) {
	resp := make([]*PlatMain, 0)
	err := m.dao.CacheSelect(redis, &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *defaultPlatMainModel) Page(page int64, size int64) *defaultPlatMainModel {
	m.dao.Page(page, size)
	return m
}

func (m *defaultPlatMainModel) Insert(data *PlatMain) (int64, error) {
	insertData, err := dao.PrepareData(data)
	if err != nil {
		return 0, err
	}
	return m.dao.Insert(insertData)
}
func (m *defaultPlatMainModel) TxInsert(tx *sql.Tx, data *PlatMain) (int64, error) {
	insertData, err := dao.PrepareData(data)
	if err != nil {
		return 0, err
	}
	return m.dao.TxInsert(tx, insertData)
}

func (m *defaultPlatMainModel) Update(data map[string]any) (int64, error) {
	return m.dao.Update(data)
}
func (m *defaultPlatMainModel) TxUpdate(tx *sql.Tx, data map[string]any) (int64, error) {
	return m.dao.TxUpdate(tx, data)
}
func (m *defaultPlatMainModel) Save(data *PlatMain) (int64, error) {
	saveData, err := dao.PrepareData(data)
	if err != nil {
		return 0, err
	}
	return m.dao.Save(saveData)
}
func (m *defaultPlatMainModel) TxSave(tx *sql.Tx, data *PlatMain) (int64, error) {
	saveData, err := dao.PrepareData(data)
	if err != nil {
		return 0, err
	}
	return m.dao.Save(saveData)
}

func (m *defaultPlatMainModel) tableName() string {
	return m.table
}

// forGoctl 避免有的model没有time.Time类型时，goctl生成模版会因引入未使用的包而报错
func (m *defaultPlatMainModel) forGoctl() {
	t := time.Time{}
	fmt.Println(t)
}
