// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"go-zero-dandan/common/dao"
	"go-zero-dandan/common/redisd"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	socialGroupMemberApplyFieldNames          = builder.RawFieldNames(&SocialGroupMemberApply{})
	socialGroupMemberApplyRows                = strings.Join(socialGroupMemberApplyFieldNames, ",")
	defaultSocialGroupMemberApplyFields       = strings.Join(socialGroupMemberApplyFieldNames, ",")
	socialGroupMemberApplyRowsExpectAutoSet   = strings.Join(stringx.Remove(socialGroupMemberApplyFieldNames, "`delete_at`"), ",")
	socialGroupMemberApplyRowsWithPlaceHolder = strings.Join(stringx.Remove(socialGroupMemberApplyFieldNames, "`id`", "`delete_at`"), "=?,") + "=?"
)

type (
	socialGroupMemberApplyModel interface {
		Insert(data *SocialGroupMemberApply) (int64, error)
		TxInsert(tx *sql.Tx, data *SocialGroupMemberApply) (int64, error)
		Update(data map[string]any) (int64, error)
		TxUpdate(tx *sql.Tx, data map[string]any) (int64, error)
		Save(data *SocialGroupMemberApply) (int64, error)
		TxSave(tx *sql.Tx, data *SocialGroupMemberApply) (int64, error)
		Delete(ctx context.Context, id int64) error
		Field(field string) *defaultSocialGroupMemberApplyModel
		Alias(alias string) *defaultSocialGroupMemberApplyModel
		Where(whereStr string, whereData ...any) *defaultSocialGroupMemberApplyModel
		WhereId(id int64) *defaultSocialGroupMemberApplyModel
		Order(order string) *defaultSocialGroupMemberApplyModel
		Limit(num int64) *defaultSocialGroupMemberApplyModel
		Plat(id int64) *defaultSocialGroupMemberApplyModel
		Find() (*SocialGroupMemberApply, error)
		FindById(id int64) (*SocialGroupMemberApply, error)
		CacheFind(redis *redisd.Redisd) (*SocialGroupMemberApply, error)
		CacheFindById(redis *redisd.Redisd, id int64) (*SocialGroupMemberApply, error)
		Page(page int64, rows int64) *defaultSocialGroupMemberApplyModel
		Select() ([]*SocialGroupMemberApply, error)
		SelectWithTotal() ([]*SocialGroupMemberApply, int64, error)
		CacheSelect(redis *redisd.Redisd) ([]*SocialGroupMemberApply, error)
		Count() (int64, error)
		Inc(field string, num int) (int64, error)
		Dec(field string, num int) (int64, error)
		Ctx(ctx context.Context) *defaultSocialGroupMemberApplyModel
		Reinit() *defaultSocialGroupMemberApplyModel
		Dao() *dao.SqlxDao
	}

	defaultSocialGroupMemberApplyModel struct {
		conn            sqlx.SqlConn
		table           string
		dao             *dao.SqlxDao
		softDeleteField string
		softDeletable   bool
		fieldSql        string
		whereSql        string
		aliasSql        string
		orderSql        string
		platId          int64
		whereData       []any
		err             error
		ctx             context.Context
	}

	SocialGroupMemberApply struct {
		Id             int64  `db:"id"`
		ApplyId        int64  `db:"apply_id"`         // 申请ID
		GroupId        int64  `db:"group_id"`         // 群组id
		UserId         int64  `db:"user_id"`          // 用户id
		ApplyMsg       string `db:"apply_msg"`        // 申请内容
		ApplyAt        int64  `db:"apply_at"`         // 申请时间
		JoinSourceEm   int64  `db:"join_source_em"`   // 加入方式
		InviteUserId   int64  `db:"invite_user_id"`   // 邀请人用户id
		ProcessUserId  int64  `db:"process_user_id"`  // 操作人用户id
		ProcessAt      int64  `db:"process_at"`       // 操作时间
		ProcessStateEm int64  `db:"process_state_em"` // 处理结果
		Remark         string `db:"remark"`           // 备注
		PlatId         int64  `db:"plat_id"`          // 应用id
		CreateAt       int64  `db:"create_at"`        // 创建时间戳
		UpdateAt       int64  `db:"update_at"`        // 更新时间戳
		DeleteAt       int64  `db:"delete_at"`        // 删除时间戳
	}
)

func newSocialGroupMemberApplyModel(conn sqlx.SqlConn, platId int64) *defaultSocialGroupMemberApplyModel {
	dao := dao.NewSqlxDao(conn, "`social_group_member_apply`", defaultSocialGroupMemberApplyFields, true, "delete_at")
	dao.Plat(platId)
	return &defaultSocialGroupMemberApplyModel{
		conn:            conn,
		dao:             dao,
		table:           "`social_group_member_apply`",
		platId:          platId,
		softDeleteField: "delete_at",
		whereData:       make([]any, 0),
	}
}
func (m *defaultSocialGroupMemberApplyModel) Ctx(ctx context.Context) *defaultSocialGroupMemberApplyModel {
	m.dao.Ctx(ctx)
	return m
}
func (m *defaultSocialGroupMemberApplyModel) WhereId(id int64) *defaultSocialGroupMemberApplyModel {
	m.dao.WhereId(id)
	return m
}

func (m *defaultSocialGroupMemberApplyModel) Where(whereStr string, whereData ...any) *defaultSocialGroupMemberApplyModel {
	m.dao.Where(whereStr, whereData...)
	return m
}

func (m *defaultSocialGroupMemberApplyModel) Alias(alias string) *defaultSocialGroupMemberApplyModel {
	m.dao.Alias(alias)
	return m
}
func (m *defaultSocialGroupMemberApplyModel) Field(field string) *defaultSocialGroupMemberApplyModel {
	m.dao.Field(field)
	return m
}
func (m *defaultSocialGroupMemberApplyModel) Order(order string) *defaultSocialGroupMemberApplyModel {
	m.dao.Order(order)
	return m
}
func (m *defaultSocialGroupMemberApplyModel) Limit(num int64) *defaultSocialGroupMemberApplyModel {
	m.dao.Limit(num)
	return m
}
func (m *defaultSocialGroupMemberApplyModel) Count() (int64, error) {
	return m.dao.Count()
}
func (m *defaultSocialGroupMemberApplyModel) Inc(field string, num int) (int64, error) {
	return m.dao.Inc(field, num)
}
func (m *defaultSocialGroupMemberApplyModel) TxInc(tx *sql.Tx, field string, num int) (int64, error) {
	return m.dao.TxInc(tx, field, num)
}
func (m *defaultSocialGroupMemberApplyModel) Dec(field string, num int) (int64, error) {
	return m.dao.Dec(field, num)
}
func (m *defaultSocialGroupMemberApplyModel) TxDec(tx *sql.Tx, field string, num int) (int64, error) {
	return m.dao.Dec(field, num)
}
func (m *defaultSocialGroupMemberApplyModel) Plat(id int64) *defaultSocialGroupMemberApplyModel {
	m.dao.Plat(id)
	return m
}
func (m *defaultSocialGroupMemberApplyModel) Reinit() *defaultSocialGroupMemberApplyModel {
	m.dao.Reinit()
	return m
}
func (m *defaultSocialGroupMemberApplyModel) Dao() *dao.SqlxDao {
	return m.dao
}
func (m *defaultSocialGroupMemberApplyModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultSocialGroupMemberApplyModel) Find() (*SocialGroupMemberApply, error) {
	resp := &SocialGroupMemberApply{}
	err := m.dao.Find(resp)
	if err != nil {
		if err == sqlx.ErrNotFound {
			return nil, nil
		}
		return nil, err
	}
	return resp, nil
}
func (m *defaultSocialGroupMemberApplyModel) FindById(id int64) (*SocialGroupMemberApply, error) {
	resp := &SocialGroupMemberApply{}
	err := m.dao.FindById(resp, id)
	if err != nil {
		if err == sqlx.ErrNotFound {
			return nil, nil
		}
		return nil, err
	}
	return resp, nil
}
func (m *defaultSocialGroupMemberApplyModel) CacheFind(redis *redisd.Redisd) (*SocialGroupMemberApply, error) {
	resp := &SocialGroupMemberApply{}
	err := m.dao.CacheFind(redis, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
func (m *defaultSocialGroupMemberApplyModel) CacheFindById(redis *redisd.Redisd, id int64) (*SocialGroupMemberApply, error) {
	resp := &SocialGroupMemberApply{}
	err := m.dao.CacheFindById(redis, resp, id)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *defaultSocialGroupMemberApplyModel) Select() ([]*SocialGroupMemberApply, error) {
	resp := make([]*SocialGroupMemberApply, 0)
	err := m.dao.Select(&resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
func (m *defaultSocialGroupMemberApplyModel) SelectWithTotal() ([]*SocialGroupMemberApply, int64, error) {
	resp := make([]*SocialGroupMemberApply, 0)
	var total int64
	err := m.dao.Select(&resp, &total)
	if err != nil {
		return nil, 0, err
	}
	return resp, total, nil
}
func (m *defaultSocialGroupMemberApplyModel) CacheSelect(redis *redisd.Redisd) ([]*SocialGroupMemberApply, error) {
	resp := make([]*SocialGroupMemberApply, 0)
	err := m.dao.CacheSelect(redis, &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *defaultSocialGroupMemberApplyModel) Page(page int64, size int64) *defaultSocialGroupMemberApplyModel {
	m.dao.Page(page, size)
	return m
}

func (m *defaultSocialGroupMemberApplyModel) Insert(data *SocialGroupMemberApply) (int64, error) {
	insertData, err := dao.PrepareData(data)
	if err != nil {
		return 0, err
	}
	return m.dao.Insert(insertData)
}
func (m *defaultSocialGroupMemberApplyModel) TxInsert(tx *sql.Tx, data *SocialGroupMemberApply) (int64, error) {
	insertData, err := dao.PrepareData(data)
	if err != nil {
		return 0, err
	}
	return m.dao.TxInsert(tx, insertData)
}

func (m *defaultSocialGroupMemberApplyModel) Update(data map[string]any) (int64, error) {
	return m.dao.Update(data)
}
func (m *defaultSocialGroupMemberApplyModel) TxUpdate(tx *sql.Tx, data map[string]any) (int64, error) {
	return m.dao.TxUpdate(tx, data)
}
func (m *defaultSocialGroupMemberApplyModel) Save(data *SocialGroupMemberApply) (int64, error) {
	saveData, err := dao.PrepareData(data)
	if err != nil {
		return 0, err
	}
	return m.dao.Save(saveData)
}
func (m *defaultSocialGroupMemberApplyModel) TxSave(tx *sql.Tx, data *SocialGroupMemberApply) (int64, error) {
	saveData, err := dao.PrepareData(data)
	if err != nil {
		return 0, err
	}
	return m.dao.Save(saveData)
}

func (m *defaultSocialGroupMemberApplyModel) tableName() string {
	return m.table
}

// forGoctl 避免有的model没有time.Time类型时，goctl生成模版会因引入未使用的包而报错
func (m *defaultSocialGroupMemberApplyModel) forGoctl() {
	t := time.Time{}
	fmt.Println(t)
}
