Err = "Encountered a small problem, please try again later"
ReqFieldRequired = "{{.Field1}} is required"
ReqPhoneErr = "Not a correct phone number"
ReqGetPhoneVerifyCodeWait = "Too many requests for verification code. Please try again later"
ReqGetPhoneVerifyCodeDayLimit="Too many requests for verification code today. Please try again tomorrow."
ReqGetPhoneVerifyCodeHourLimit="Too many requests for verification in a hour. Please try again later."

ConfigNotInit = "Not set {{.Field1}}"
PlatInvalid = "Invalid App"
PlatIdErr = "Invalid App Id"
PlatClasErr = "Invalid App Clas"
RedisSetErr = "Redis set fail"
RedisGetErr = "Redis get fail"

NotFound = "Data not found"
NotFoundUser = "User not found"

DataExist1 = "The {{.Field1}} already exists"

NotSupportPhoneArea =  "Unsupported phone number"
NotSupportFileType =  "Unsupported file type"
NotSupportImageType = "Unsupported image type"
UploadFileFail = "Upload file fail"

ImageSizeLimited1 = "image size is limited to {{.Field1}} or less"
AccountOrPassWrong = "Account or password is wrong"
VerifyCodeWrong = "Verify code is wrong"
VerifyCodeExpired = "Please obtain the verification code first"
Success = "Success"
SuccessAsync = "Submit Finish"

PhoneNumber = "Phone Number"
SmsTemp ="Sms Template"
MessageSysConfig = "Message Center Config"
Data = "Data"
Image = "Image"







[MyUnreadEmails]
description = "The number of unread emails I have"
one = "I have {{.PluralCount}} unread email."
other = "I have {{.PluralCount}} unread emails."

[PersonUnreadEmails]
description = "The number of unread emails a person has"
one = "{{.Name}} has {{.UnreadEmailCount}} unread email."
other = "{{.Name}} has {{.UnreadEmailCount}} unread emails."


