Err = "Encountered a small problem, please try again later"
ReqFieldRequired = "{{.Field1}} is required"
ReqPhoneErr = "Not a correct phone number"
ReqGetPhoneVerifyCodeWait = "Too many requests for verification code. Please try again later"
ReqGetPhoneVerifyCodeDayLimit="Too many requests for verification code today. Please try again tomorrow."
ReqGetPhoneVerifyCodeHourLimit="Too many requests for verification in a hour. Please try again later."

ConfigNotInit = "Not set {{.Field1}}"
PlatInvalid = "Invalid App"
PlatIdErr = "Invalid App Id"
PlatClasErr = "Invalid App Clas"
RedisSetErr = "Redis set fail"
RedisGetErr = "Redis get fail"



Success = "Success"
SuccessAsync = "Submit Finish"

PhoneNumber = "Phone Number"
SmsTemp ="Sms Template"
MessageSysConfig = "Message Center Config"








[MyUnreadEmails]
description = "The number of unread emails I have"
one = "I have {{.PluralCount}} unread email."
other = "I have {{.PluralCount}} unread emails."

[PersonUnreadEmails]
description = "The number of unread emails a person has"
one = "{{.Name}} has {{.UnreadEmailCount}} unread email."
other = "{{.Name}} has {{.UnreadEmailCount}} unread emails."


