AuthUserNotLoginErr = "You are not login"
AuthPlatErr = "invalid App"
SysErr = "Encountered a small problem"

CopierErr = "copy data trans error"
NotFound1 = "{{.Field1}} is not found"

ReqFieldRequired1 = "Param {{.Field1}} is required"
ReqPhoneErr = "Not a correct phone number"
ReqGetPhoneVerifyCodeWait = "Too many requests for verification code. Please try again later"
ReqGetPhoneVerifyCodeDayLimit="Too many requests for verification code today. Please try again tomorrow."
ReqGetPhoneVerifyCodeHourLimit="Too many requests for verification in a hour. Please try again later."
ReqParamFormatErr1 = "{{.Field1}} does not meet the requirements"

ConfigNotInit1 = "Not set {{.Field1}}"
PlatInvalid = "Invalid App"
PlatIdErr = "Invalid App Id"
PlatClasErr = "Invalid App Clas"


MysqlErr = "Mysql error"
MysqlInsertErr = "Mysql insert error"
MysqlUpdateErr = "Mysql update error"
MysqlSelectErr = "Mysql select error"
MysqlDeleteErr = "Mysql delete error"
MysqlStartTransErr = "Mysql start trans error"
MysqlCommitErr = "Mysql commit trans error"
MysqlRollbackErr = "Mysql rollback trans error"


RedisSetErr = "Redis set fail"
RedisGetErr = "Redis get fail"

NotFound = "Data not found"
NotFoundUser = "User not found"

DataExist1 = "The {{.Field1}} already exists"

NotSupportPhoneArea =  "Unsupported phone number"
NotSupportFileType =  "Unsupported file type"
NotSupportImageType = "Unsupported image type"
UploadFileFail = "Upload file fail"

UploadImageSizeLimited1 = "image size is limited to {{.Field1}} or less"
UploadFileSizeLimited1 = "file size is limited to {{.Field1}} or less"
UploadImageTypeLimited1 = "image type limited {{.Field1}}"
UploadFileTypeLimited1 = "file type limited {{.Field1}}"
MergeFileChunkNotFound = "not found merge files"

MultipartUploadFileHashRequired = "multipart upload file sha1 hash is required"
MultipartUploadNotComplete = "multipart upload file not all complete"


AccountOrPassWrong = "Account or password is wrong"
VerifyCodeWrong = "Verify code is wrong"
VerifyCodeExpired = "Please obtain the verification code first"
Success = "Success"
SuccessAsync = "Submit Finish"

PhoneNumber = "Phone Number"
SmsTemp ="Sms Template"
MessageSysConfig = "Message Center Config"
Data = "Data"
Image = "Image"
Id = "Id"
Account = "Account"
Password = "Password"
UpoladTask = "Upload Task"




[MyUnreadEmails]
description = "The number of unread emails I have"
one = "I have {{.PluralCount}} unread email."
other = "I have {{.PluralCount}} unread emails."

[PersonUnreadEmails]
description = "The number of unread emails a person has"
one = "{{.Name}} has {{.UnreadEmailCount}} unread email."
other = "{{.Name}} has {{.UnreadEmailCount}} unread emails."


