// Code generated by goctl. DO NOT EDIT.
package logic

import (
	"context"

	"go-zero-dandan/app/dify/api/internal/svc"
	"go-zero-dandan/app/dify/api/internal/types"

	"github.com/zeromicro/go-zero/core/logx"
	"go-zero-dandan/common/resd"
	"go-zero-dandan/common/typed"
	"strings"
)

type ChatMessagesStreamLogicGen struct {
	logx.Logger
	ctx          context.Context
	svc          *svc.ServiceContext
	resd         *resd.Resp
	meta         *typed.ReqMeta
	hasUserInfo  bool
	mustUserInfo bool
	req          struct {
		Query string `json:"query,optional"`
	}
	hasReq struct {
		Query bool
	}
}

func NewChatMessagesStreamLogicGen(ctx context.Context, svc *svc.ServiceContext) *ChatMessagesStreamLogicGen {
	meta, _ := ctx.Value("reqMeta").(*typed.ReqMeta)
	if meta == nil {
		meta = &typed.ReqMeta{}
	}
	return &ChatMessagesStreamLogicGen{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svc:    svc,
		resd:   resd.NewResp(ctx, meta.Lang),
		meta:   meta,
	}
}

func (l *ChatMessagesStreamLogicGen) initReq(in *types.ChatMessagesReq) error {

	if in.Query != nil {
		l.req.Query = strings.TrimSpace(*in.Query)
		l.hasReq.Query = true
	} else {
		l.hasReq.Query = false
	}

	if l.hasReq.Query == false {
		return resd.NewErrWithTempCtx(l.ctx, "缺少参数Query", resd.ErrReqFieldRequired1, "Query")
	}

	if l.req.Query == "" {
		return resd.NewErrWithTempCtx(l.ctx, "Query不得为空", resd.ErrReqFieldEmpty1, "Query")
	}
	l.hasUserInfo = true
	l.mustUserInfo = true

	return nil
}
