// Code generated by goctl. DO NOT EDIT.
package logic

import (
	"context"
	"go-zero-dandan/app/social/rpc/internal/svc"
	"go-zero-dandan/app/social/rpc/types/socialRpc"
	"go-zero-dandan/common/resd"

	"github.com/zeromicro/go-zero/core/logx"
)

type CreateFriendApplyLogicGen struct {
	ctx    context.Context
	svc    *svc.ServiceContext
	resd   *resd.Resp
	lang   string
	userId string
	platId string
	logx.Logger
	ReqPlatId    string
	ReqUserId    string
	ReqFriendUid string `check:"required"`
	ReqApplyMsg  string
	ReqApplyAt   int64
	ReqSourceEm  int64
	HasReq       struct {
		PlatId    bool
		UserId    bool
		FriendUid bool
		ApplyMsg  bool
		ApplyAt   bool
		SourceEm  bool
	}
}

func NewCreateFriendApplyLogicGen(ctx context.Context, svc *svc.ServiceContext) *CreateFriendApplyLogicGen {
	lang, _ := ctx.Value("lang").(string)
	return &CreateFriendApplyLogicGen{
		ctx:    ctx,
		svc:    svc,
		Logger: logx.WithContext(ctx),
		lang:   lang,
		resd:   resd.NewResd(ctx, resd.I18n.NewLang(lang)),
	}
}

func (l *CreateFriendApplyLogicGen) initReq(req *socialRpc.CreateFriendApplyReq) error {
	var err error
	if err = l.initPlat(); err != nil {
		return l.resd.Error(err)
	}

	if req.PlatId != nil {
		l.ReqPlatId = *req.PlatId
		l.HasReq.PlatId = true
	} else {
		l.HasReq.PlatId = false
	}

	if req.UserId != nil {
		l.ReqUserId = *req.UserId
		l.HasReq.UserId = true
	} else {
		l.HasReq.UserId = false
	}

	if req.FriendUid != nil {
		l.ReqFriendUid = *req.FriendUid
		l.HasReq.FriendUid = true
	} else {
		l.HasReq.FriendUid = false
	}

	if l.HasReq.FriendUid == false {
		return l.resd.NewErrWithTemp(resd.ReqFieldRequired1, "*FriendUid")
	}

	if l.ReqFriendUid == "" {
		return l.resd.NewErrWithTemp(resd.ReqFieldEmpty1, "*FriendUid")
	}

	if req.ApplyMsg != nil {
		l.ReqApplyMsg = *req.ApplyMsg
		l.HasReq.ApplyMsg = true
	} else {
		l.HasReq.ApplyMsg = false
	}

	if req.ApplyAt != nil {
		l.ReqApplyAt = *req.ApplyAt
		l.HasReq.ApplyAt = true
	} else {
		l.HasReq.ApplyAt = false
	}

	if req.SourceEm != nil {
		l.ReqSourceEm = *req.SourceEm
		l.HasReq.SourceEm = true
	} else {
		l.HasReq.SourceEm = false
	}

	return nil
}

func (l *CreateFriendApplyLogicGen) initUser() (err error) {
	userId, _ := l.ctx.Value("userId").(string)
	l.userId = userId
	return nil
}

func (l *CreateFriendApplyLogicGen) initPlat() (err error) {
	platId, _ := l.ctx.Value("platId").(string)
	l.platId = platId
	return nil
}
