// Code generated by goctl. DO NOT EDIT.
package logic

import (
	"context"
	"go-zero-dandan/app/social/rpc/internal/svc"
	"go-zero-dandan/app/social/rpc/types/socialRpc"
	"go-zero-dandan/common/resd"
	"go-zero-dandan/common/typed"

	"github.com/zeromicro/go-zero/core/logx"
)

type OperateFriendApplyLogicGen struct {
	ctx  context.Context
	svc  *svc.ServiceContext
	resd *resd.Resp
	meta *typed.ReqMeta
	logx.Logger
	req struct {
		ApplyId        string
		OperateUid     string
		OperateStateEm int64
		PlatId         string
		OperateMsg     string
		SysRoleEm      string
		SysRoleUid     string
	}
	hasReq struct {
		ApplyId        bool
		OperateUid     bool
		OperateStateEm bool
		PlatId         bool
		OperateMsg     bool
		SysRoleEm      bool
		SysRoleUid     bool
	}
}

func NewOperateFriendApplyLogicGen(ctx context.Context, svc *svc.ServiceContext) *OperateFriendApplyLogicGen {
	meta, _ := ctx.Value("reqMeta").(*typed.ReqMeta)
	if meta == nil {
		meta = &typed.ReqMeta{}
	}
	return &OperateFriendApplyLogicGen{
		ctx:    ctx,
		svc:    svc,
		Logger: logx.WithContext(ctx),
		resd:   resd.NewResp(ctx, meta.Lang),
		meta:   meta,
	}
}

func (l *OperateFriendApplyLogicGen) initReq(in *socialRpc.OperateFriendApplyReq) error {

	if in.ApplyId != nil {
		l.req.ApplyId = *in.ApplyId
		l.hasReq.ApplyId = true
	} else {
		l.hasReq.ApplyId = false
	}

	if in.OperateUid != nil {
		l.req.OperateUid = *in.OperateUid
		l.hasReq.OperateUid = true
	} else {
		l.hasReq.OperateUid = false
	}

	if in.OperateStateEm != nil {
		l.req.OperateStateEm = *in.OperateStateEm
		l.hasReq.OperateStateEm = true
	} else {
		l.hasReq.OperateStateEm = false
	}

	if in.PlatId != nil {
		l.req.PlatId = *in.PlatId
		l.hasReq.PlatId = true
	} else {
		l.hasReq.PlatId = false
	}

	if in.OperateMsg != nil {
		l.req.OperateMsg = *in.OperateMsg
		l.hasReq.OperateMsg = true
	} else {
		l.hasReq.OperateMsg = false
	}

	if in.SysRoleEm != nil {
		l.req.SysRoleEm = *in.SysRoleEm
		l.hasReq.SysRoleEm = true
	} else {
		l.hasReq.SysRoleEm = false
	}

	if in.SysRoleUid != nil {
		l.req.SysRoleUid = *in.SysRoleUid
		l.hasReq.SysRoleUid = true
	} else {
		l.hasReq.SysRoleUid = false
	}

	return nil
}
