// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"go-zero-dandan/common/redisd"
	"strconv"
	"strings"
	"time"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messageSmsSendFieldNames          = builder.RawFieldNames(&MessageSmsSend{})
	messageSmsSendRows                = strings.Join(messageSmsSendFieldNames, ",")
	messageSmsSendRowsExpectAutoSet   = strings.Join(stringx.Remove(messageSmsSendFieldNames, "`delete_at`"), ",")
	messageSmsSendRowsWithPlaceHolder = strings.Join(stringx.Remove(messageSmsSendFieldNames, "`id`", "`delete_at`"), "=?,") + "=?"
)

type (
	messageSmsSendModel interface {
		Insert(ctx context.Context, data *MessageSmsSend) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*MessageSmsSend, error)
		Update(ctx context.Context, data *MessageSmsSend) error
		Delete(ctx context.Context, id int64) error
		Field(field string) *defaultMessageSmsSendModel
		Alias(alias string) *defaultMessageSmsSendModel
		WhereStr(whereStr string) *defaultMessageSmsSendModel
		WhereId(id int) *defaultMessageSmsSendModel
		WhereMap(whereMap map[string]any) *defaultMessageSmsSendModel
		WhereRaw(whereStr string, whereData []any) *defaultMessageSmsSendModel
		Order(order string) *defaultMessageSmsSendModel
		Plat(id int) *defaultMessageSmsSendModel
		Find(ctx context.Context, id ...any) (*MessageSmsSend, error)
		CacheFind(ctx context.Context, redis *redisd.Redisd, id ...int64) (*MessageSmsSend, error)
		Page(ctx context.Context, page int, rows int) ([]*MessageSmsSend, error)
		List(ctx context.Context) ([]*MessageSmsSend, error)
		Count(ctx context.Context) int
		Inc(ctx context.Context, field string, num int) error
		Dec(ctx context.Context, field string, num int) error
	}

	defaultMessageSmsSendModel struct {
		conn            sqlx.SqlConn
		table           string
		softDeleteField string
		SoftDeletable   bool
		fieldSql        string
		whereSql        string
		aliasSql        string
		orderSql        string
		whereData       []any
		err             error
	}

	MessageSmsSend struct {
		Id       int64  `db:"id"`
		Phone    string `db:"phone"`     // 发送手机号
		Content  string `db:"content"`   // 发送手机号
		StateEm  int64  `db:"state_em"`  // 发送状态枚举
		Err      string `db:"err"`       // 发送错误时的错误信息
		TempId   int64  `db:"temp_id"`   // 模版id
		PlatId   int64  `db:"plat_id"`   // 应用id
		CreateAt int64  `db:"create_at"` // 创建时间戳
		UpdateAt int64  `db:"update_at"` // 更新时间戳
		DeleteAt int64  `db:"delete_at"` // 删除时间戳
	}
)

func newMessageSmsSendModel(conn sqlx.SqlConn) *defaultMessageSmsSendModel {
	return &defaultMessageSmsSendModel{
		conn:            conn,
		table:           "`message_sms_send`",
		softDeleteField: "delete_at",
		whereData:       make([]any, 0),
	}
}

func (m *defaultMessageSmsSendModel) WhereId(id int) *defaultMessageSmsSendModel {
	m.whereSql = "id=?"
	m.whereData = append(m.whereData, id)
	return m
}

func (m *defaultMessageSmsSendModel) WhereStr(whereStr string) *defaultMessageSmsSendModel {
	if m.whereSql != "" {
		m.whereSql += " AND (" + whereStr + ")"
	} else {
		m.whereSql = "(" + whereStr + ")"
	}
	return m
}

func (m *defaultMessageSmsSendModel) WhereMap(whereMap map[string]any) *defaultMessageSmsSendModel {
	return m
}
func (m *defaultMessageSmsSendModel) WhereRaw(whereStr string, whereData []any) *defaultMessageSmsSendModel {
	if m.whereSql != "" {
		m.whereSql += " AND (" + whereStr + ")"
	} else {
		m.whereSql = "(" + whereStr + ")"
	}
	m.whereData = append(m.whereData, whereData...)
	return m
}
func (m *defaultMessageSmsSendModel) Alias(field string) *defaultMessageSmsSendModel {
	m.aliasSql = field
	return m
}
func (m *defaultMessageSmsSendModel) Field(field string) *defaultMessageSmsSendModel {
	m.fieldSql = field
	return m
}
func (m *defaultMessageSmsSendModel) Order(order string) *defaultMessageSmsSendModel {

	return m
}
func (m *defaultMessageSmsSendModel) Count(ctx context.Context) int {

	return 0
}
func (m *defaultMessageSmsSendModel) Inc(ctx context.Context, field string, num int) error {

	return nil
}
func (m *defaultMessageSmsSendModel) Dec(ctx context.Context, field string, num int) error {

	return nil
}
func (m *defaultMessageSmsSendModel) Plat(id int) *defaultMessageSmsSendModel {

	return nil
}
func (m *defaultMessageSmsSendModel) CacheFind(ctx context.Context, redis *redisd.Redisd, id ...int64) (*MessageSmsSend, error) {
	resp := &MessageSmsSend{}
	cacheField := "model_" + m.tableName()
	cacheKey := strconv.FormatInt(id[0], 10)
	// todo::需要把where条件一起放进去作为key，这样就能支持更多的自动缓存查询
	err := redis.GetData(cacheField, cacheKey, resp)
	if err == nil {
		return resp, nil
	}
	resp, err = m.Find(ctx, id[0])
	fmt.Println(resp, err)
	if err != nil {
		return resp, err
	}
	if resp.Id != 0 {
		redis.SetData(cacheField, cacheKey, resp)
	}
	return resp, nil
}

func (m *defaultMessageSmsSendModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMessageSmsSendModel) Find(ctx context.Context, id ...any) (*MessageSmsSend, error) {
	defer m.Reinit()
	var err error
	if err = m.err; err != nil {
		m.err = nil
		return nil, err
	}
	var resp MessageSmsSend
	var sql string
	field := messageSmsSendRows
	if m.fieldSql != "" {
		field = m.fieldSql
	}
	if len(id) > 0 {
		sql = fmt.Sprintf("select %s from %s where id=? limit 1", field, m.table)
		err = m.conn.QueryRowPartialCtx(ctx, &resp, sql, id[0]) //QueryRowCtx 必须字段都覆盖
	} else {
		if m.whereSql == "" {
			m.whereSql = "1=1"
		}
		sql = fmt.Sprintf("select %s from %s %s where "+m.whereSql+" limit 1", field, m.table, m.aliasSql)
		err = m.conn.QueryRowPartialCtx(ctx, &resp, sql, m.whereData...)
	}
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return &resp, nil
	default:
		return nil, err
	}
}
func (m *defaultMessageSmsSendModel) List(ctx context.Context) ([]*MessageSmsSend, error) {
	defer m.Reinit()
	var err error
	if err = m.err; err != nil {
		m.err = nil
		return nil, err
	}
	var resp []*MessageSmsSend
	var sql string
	field := messageSmsSendRows
	if m.fieldSql != "" {
		field = m.fieldSql
	}
	if m.whereSql == "" {
		m.whereSql = "1=1"
	}
	sql = fmt.Sprintf("select %s from %s %s where "+m.whereSql, field, m.table, m.aliasSql)
	err = m.conn.QueryRowsPartialCtx(ctx, &resp, sql, m.whereData...)
	switch err {
	case nil:
		return resp, nil
	case sqlx.ErrNotFound:
		return resp, nil
	default:
		return nil, err
	}
}
func (m *defaultMessageSmsSendModel) Page(ctx context.Context, page int, rows int) ([]*MessageSmsSend, error) {
	defer m.Reinit()
	return nil, nil
}
func (m *defaultMessageSmsSendModel) FindOne(ctx context.Context, id int64) (*MessageSmsSend, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", messageSmsSendRows, m.table)
	var resp MessageSmsSend
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlx.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}
func (m *defaultMessageSmsSendModel) Reinit() {
	m.whereSql = ""
	m.fieldSql = ""
	m.aliasSql = ""
	m.orderSql = ""
	m.whereData = make([]any, 0)
	m.err = nil
}

func (m *defaultMessageSmsSendModel) Insert(ctx context.Context, data *MessageSmsSend) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?, ?, ?, ?, ?, ?, ?)", m.table, messageSmsSendRowsExpectAutoSet)
	data.CreateAt = time.Now().Unix()
	data.UpdateAt = time.Now().Unix()
	ret, err := m.conn.ExecCtx(ctx, query, data.Id, data.Phone, data.Content, data.StateEm, data.Err, data.TempId, data.PlatId, data.CreateAt, data.UpdateAt)
	return ret, err
}

func (m *defaultMessageSmsSendModel) Update(ctx context.Context, data *MessageSmsSend) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, messageSmsSendRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Phone, data.Content, data.StateEm, data.Err, data.TempId, data.PlatId, data.CreateAt, data.UpdateAt, data.Id)
	return err
}

func (m *defaultMessageSmsSendModel) tableName() string {
	return m.table
}
