// Code generated by goctl. DO NOT EDIT.

package model

import (
	"context"
	"database/sql"
	"fmt"
	"go-zero-dandan/common/dao"
	"go-zero-dandan/common/redisd"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	messageSmsSendFieldNames          = builder.RawFieldNames(&MessageSmsSend{})
	messageSmsSendRows                = strings.Join(messageSmsSendFieldNames, ",")
	defaultMessageSmsSendFields       = strings.Join(messageSmsSendFieldNames, ",")
	messageSmsSendRowsExpectAutoSet   = strings.Join(stringx.Remove(messageSmsSendFieldNames, "`delete_at`"), ",")
	messageSmsSendRowsWithPlaceHolder = strings.Join(stringx.Remove(messageSmsSendFieldNames, "`id`", "`delete_at`"), "=?,") + "=?"
)

type (
	messageSmsSendModel interface {
		Insert(data map[string]string) (int64, error)
		TxInsert(tx *sql.Tx, data map[string]string) (int64, error)
		Update(data map[string]string) (int64, error)
		TxUpdate(tx *sql.Tx, data map[string]string) (int64, error)
		Save(data map[string]string) (int64, error)
		TxSave(tx *sql.Tx, data map[string]string) (int64, error)
		Delete(ctx context.Context, id int64) error
		Field(field string) *defaultMessageSmsSendModel
		Alias(alias string) *defaultMessageSmsSendModel
		Where(whereStr string, whereData ...any) *defaultMessageSmsSendModel
		WhereId(id int64) *defaultMessageSmsSendModel
		Order(order string) *defaultMessageSmsSendModel
		Limit(num int64) *defaultMessageSmsSendModel
		Plat(id int64) *defaultMessageSmsSendModel
		Find() (*MessageSmsSend, error)
		FindById(id int64) (*MessageSmsSend, error)
		CacheFind(redis *redisd.Redisd) (*MessageSmsSend, error)
		CacheFindById(redis *redisd.Redisd, id int64) (*MessageSmsSend, error)
		Page(page int64, rows int64) *defaultMessageSmsSendModel
		Select() ([]*MessageSmsSend, error)
		SelectWithTotal() ([]*MessageSmsSend, int64, error)
		CacheSelect(redis *redisd.Redisd) ([]*MessageSmsSend, error)
		Count() (int64, error)
		Inc(field string, num int) (int64, error)
		Dec(field string, num int) (int64, error)
		Ctx(ctx context.Context) *defaultMessageSmsSendModel
		Reinit() *defaultMessageSmsSendModel
		Dao() *dao.SqlxDao
	}

	defaultMessageSmsSendModel struct {
		conn            sqlx.SqlConn
		table           string
		dao             *dao.SqlxDao
		softDeleteField string
		softDeletable   bool
		fieldSql        string
		whereSql        string
		aliasSql        string
		orderSql        string
		platId          int64
		whereData       []any
		err             error
		ctx             context.Context
	}

	MessageSmsSend struct {
		Id       int64  `db:"id"`
		Phone    string `db:"phone"`     // 发送手机号
		Content  string `db:"content"`   // 发送手机号
		StateEm  int64  `db:"state_em"`  // 发送状态枚举
		Err      string `db:"err"`       // 发送错误时的错误信息
		TempId   int64  `db:"temp_id"`   // 模版id
		PlatId   int64  `db:"plat_id"`   // 应用id
		CreateAt int64  `db:"create_at"` // 创建时间戳
		UpdateAt int64  `db:"update_at"` // 更新时间戳
		DeleteAt int64  `db:"delete_at"` // 删除时间戳
	}
)

func newMessageSmsSendModel(conn sqlx.SqlConn, platId int64) *defaultMessageSmsSendModel {
	dao := dao.NewSqlxDao(conn, "`message_sms_send`", defaultMessageSmsSendFields, true, "delete_at")
	dao.Plat(platId)
	return &defaultMessageSmsSendModel{
		conn:            conn,
		dao:             dao,
		table:           "`message_sms_send`",
		platId:          platId,
		softDeleteField: "delete_at",
		whereData:       make([]any, 0),
	}
}
func (m *defaultMessageSmsSendModel) Ctx(ctx context.Context) *defaultMessageSmsSendModel {
	m.dao.Ctx(ctx)
	return m
}
func (m *defaultMessageSmsSendModel) WhereId(id int64) *defaultMessageSmsSendModel {
	m.dao.WhereId(id)
	return m
}

func (m *defaultMessageSmsSendModel) Where(whereStr string, whereData ...any) *defaultMessageSmsSendModel {
	m.dao.Where(whereStr, whereData...)
	return m
}

func (m *defaultMessageSmsSendModel) Alias(alias string) *defaultMessageSmsSendModel {
	m.dao.Alias(alias)
	return m
}
func (m *defaultMessageSmsSendModel) Field(field string) *defaultMessageSmsSendModel {
	m.dao.Field(field)
	return m
}
func (m *defaultMessageSmsSendModel) Order(order string) *defaultMessageSmsSendModel {
	m.dao.Order(order)
	return m
}
func (m *defaultMessageSmsSendModel) Limit(num int64) *defaultMessageSmsSendModel {
	m.dao.Limit(num)
	return m
}
func (m *defaultMessageSmsSendModel) Count() (int64, error) {
	return m.dao.Count()
}
func (m *defaultMessageSmsSendModel) Inc(field string, num int) (int64, error) {
	return m.dao.Inc(field, num)
}
func (m *defaultMessageSmsSendModel) TxInc(tx *sql.Tx, field string, num int) (int64, error) {
	return m.dao.TxInc(tx, field, num)
}
func (m *defaultMessageSmsSendModel) Dec(field string, num int) (int64, error) {
	return m.dao.Dec(field, num)
}
func (m *defaultMessageSmsSendModel) TxDec(tx *sql.Tx, field string, num int) (int64, error) {
	return m.dao.Dec(field, num)
}
func (m *defaultMessageSmsSendModel) Plat(id int64) *defaultMessageSmsSendModel {
	m.dao.Plat(id)
	return m
}
func (m *defaultMessageSmsSendModel) Reinit() *defaultMessageSmsSendModel {
	m.dao.Reinit()
	return m
}
func (m *defaultMessageSmsSendModel) Dao() *dao.SqlDao {
	return m.dao
}
func (m *defaultMessageSmsSendModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultMessageSmsSendModel) Find() (*MessageSmsSend, error) {
	resp := &MessageSmsSend{}
	err := m.dao.Find(resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
func (m *defaultMessageSmsSendModel) FindById(id int64) (*MessageSmsSend, error) {
	resp := &MessageSmsSend{}
	err := m.dao.FindById(resp, id)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
func (m *defaultMessageSmsSendModel) CacheFind(redis *redisd.Redisd) (*MessageSmsSend, error) {
	resp := &MessageSmsSend{}
	err := m.dao.CacheFind(redis, resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
func (m *defaultMessageSmsSendModel) CacheFindById(redis *redisd.Redisd, id int64) (*MessageSmsSend, error) {
	resp := &MessageSmsSend{}
	err := m.dao.CacheFindById(redis, resp, id)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *defaultMessageSmsSendModel) Select() ([]*MessageSmsSend, error) {
	resp := make([]*MessageSmsSend, 0)
	err := m.dao.Select(&resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}
func (m *defaultMessageSmsSendModel) SelectWithTotal() ([]*MessageSmsSend, int64, error) {
	resp := make([]*MessageSmsSend, 0)
	var total int64
	err := m.dao.Select(&resp, &total)
	if err != nil {
		return nil, 0, err
	}
	return resp, total, nil
}
func (m *defaultMessageSmsSendModel) CacheSelect(redis *redisd.Redisd) ([]*MessageSmsSend, error) {
	resp := make([]*MessageSmsSend, 0)
	err := m.dao.CacheSelect(redis, &resp)
	if err != nil {
		return nil, err
	}
	return resp, nil
}

func (m *defaultMessageSmsSendModel) Page(page int64, rows int64) *defaultMessageSmsSendModel {
	m.dao.Page(page, rows)
	return m
}

func (m *defaultMessageSmsSendModel) Insert(data map[string]string) (int64, error) {
	return m.dao.Insert(data)
}
func (m *defaultMessageSmsSendModel) TxInsert(tx *sql.Tx, data map[string]string) (int64, error) {
	return m.dao.TxInsert(tx, data)
}

func (m *defaultMessageSmsSendModel) Update(data map[string]string) (int64, error) {
	return m.dao.Update(data)
}
func (m *defaultMessageSmsSendModel) TxUpdate(tx *sql.Tx, data map[string]string) (int64, error) {
	return m.dao.TxUpdate(tx, data)
}
func (m *defaultMessageSmsSendModel) Save(data map[string]string) (int64, error) {
	return m.dao.Save(data)
}
func (m *defaultMessageSmsSendModel) TxSave(tx *sql.Tx, data map[string]string) (int64, error) {
	return m.dao.Save(data)
}

func (m *defaultMessageSmsSendModel) tableName() string {
	return m.table
}
