Ok = "成功"


ErrAccountOrPassWrong = ""
ErrAuth = ""
ErrAuthOperateState = ""
ErrAuthOperateUser = ""
ErrAuthPlat = ""
ErrAuthUserNotLogin = ""
ErrConfigNotInit1 = ""
ErrCopier = ""
ErrCreateConversation = ""
ErrDataBiz = ""
ErrDataExist1 = ""
ErrMergeFileChunkNotFound = ""
ErrMqPush = ""
ErrMultipartUploadFileHashRequired = ""
ErrMultipartUploadNotComplete = ""
ErrMysql = ""
ErrMysqlCommit = ""
ErrMysqlDelete = ""
ErrMysqlInsert = ""
ErrMysqlRollback = ""
ErrMysqlSelect = ""
ErrMysqlStartTrans = ""
ErrMysqlUpdate = ""
ErrNotFound1 = ""
ErrNotFoundUser = ""
ErrNotSupportFileType = ""
ErrNotSupportImageType = ""
ErrNotSupportPhoneArea = ""
ErrPlatClas = ""
ErrPlatId = ""
ErrPlatInvalid = ""
ErrRedis = ""
ErrRedisDec = ""
ErrRedisGet = ""
ErrRedisGetUserToken = ""
ErrRedisInc = ""
ErrRedisSet = ""
ErrRedisSetUserLoginState = ""
ErrRedisSetVerifyCode = ""
ErrRedisSetVerifyCodeInterval = ""
ErrReqFieldEmpty1 = ""
ErrReqFieldRequired1 = ""
ErrReqGetPhoneVerifyCodeDayLimit = ""
ErrReqGetPhoneVerifyCodeHourLimit = ""
ErrReqGetPhoneVerifyCodeWait = ""
ErrReqKeyRequired = ""
ErrReqParam = ""
ErrReqParamFormat1 = ""
ErrReqPhone = ""
ErrReqRateLimit = ""
ErrReqWait = ""
ErrRpcResDecode = ""
ErrSocialAlreadyBlackMe = ""
ErrSocialAlreadyFriend = ""
ErrSocialNotAddSelf = ""
ErrSys = ""
ErrTrdSmsSend = ""
ErrUploadFileFail = ""
ErrUploadFileSizeLimited1 = ""
ErrUploadFileTypeLimited1 = ""
ErrUploadImageSizeLimited1 = ""
ErrUploadImageTypeLimited1 = ""
ErrUserMainInfo = ""
ErrVerifyCodeExpired = ""
ErrVerifyCodeWrong = ""
OkAsync = ""
VarAccount = ""
VarData = ""
VarId = ""
VarImage = ""
VarMessageSysConfig = ""
VarPassword = ""
VarPhoneNumber = ""
VarSmsTemp = ""
VarUpoladTask = ""
VarUrl = ""
