AccountOrPassWrong = "Account or password is wrong"
AuthPlatErr = "invalid App"
AuthUserNotLoginErr = "You are not login"
ConfigNotInit1 = "Not set {{.Field1}}"
CopierErr = "copy data trans error"
DataExist1 = "The {{.Field1}} already exists"
MergeFileChunkNotFound = "not found merge files"
MultipartUploadFileHashRequired = "multipart upload file sha1 hash is required"
MultipartUploadNotComplete = "multipart upload file not all complete"
MysqlCommitErr = "Mysql commit trans error"
MysqlDeleteErr = "Mysql delete error"
MysqlErr = "Mysql error"
MysqlInsertErr = "Mysql insert error"
MysqlRollbackErr = "Mysql rollback trans error"
MysqlSelectErr = "Mysql select error"
MysqlStartTransErr = "Mysql start trans error"
MysqlUpdateErr = "Mysql update error"
NotFound1 = "{{.Field1}} is not found"
NotFoundUser = "User not found"
NotSupportFileType = "Unsupported file type"
NotSupportImageType = "Unsupported image type"
NotSupportPhoneArea = "Unsupported phone number"
Ok = "成功"
PlatClasErr = "Invalid App Clas"
PlatIdErr = "Invalid App Id"
PlatInvalid = "Invalid App"
RedisGetErr = "Redis get fail"
RedisSetErr = "Redis set fail"
ReqFieldEmpty1 = "Param {{.Field1}} is empty"
ReqFieldRequired1 = "Param {{.Field1}} is required"
ReqGetPhoneVerifyCodeDayLimit = "Too many requests for verification code today. Please try again tomorrow."
ReqGetPhoneVerifyCodeHourLimit = "Too many requests for verification in a hour. Please try again later."
ReqGetPhoneVerifyCodeWait = "Too many requests for verification code. Please try again later"
ReqParamFormatErr1 = "{{.Field1}} does not meet the requirements"
ReqPhoneErr = "Not a correct phone number"
SocialAlreadyBlackMe = "You are blacked"
SocialAlreadyFriend = "Already Friend"
SocialNotAddSelf = "Cannot add yourself"
SysErr = "Encountered a small problem"
UploadFileFail = "Upload file fail"
UploadFileSizeLimited1 = "file size is limited to {{.Field1}} or less"
UploadFileTypeLimited1 = "file type limited {{.Field1}}"
UploadImageSizeLimited1 = "image size is limited to {{.Field1}} or less"
UploadImageTypeLimited1 = "image type limited {{.Field1}}"
VerifyCodeExpired = "Please obtain the verification code first"
VerifyCodeWrong = "Verify code is wrong"
Account = "Account"
Data = "Data"
Id = "Id"
Image = "Image"
MessageSysConfig = "Message Center Config"
PhoneNumber = "Phone Number"
SmsTemp = "Sms Template"
UpoladTask = "Upload Task"


Auth = ""
AuthOperateStateErr = ""
AuthOperateUserErr = ""
DataBizErr = ""
MqPushErr = ""
OkAsync = ""
RedisDecErr = ""
RedisErr = ""
RedisGetUserTokenErr = ""
RedisIncErr = ""
RedisSetUserLoginStateErr = ""
RedisSetVerifyCodeErr = ""
RedisSetVerifyCodeIntervalErr = ""
ReqKeyRequired = ""
ReqParamErr = ""
ReqWait = ""
RpcResDecodeErr = ""
TrdSmsSendErr = ""
UserMainInfoErr = ""
VarPassword = ""
