AuthUserNotLoginErr = "您还未登录"
AuthPlatErr = "无效应用"
SysErr = "遇到了点小问题"
DataBizErr = "业务数据异常"

CopierErr = "内部数据格式转换失败"
NotFound1 = "{{.Field1}}不存在"

ReqFieldRequired1 = "缺少参数{{.Field1}}"
ReqFieldEmpty1 = "{{.Field1}}不能为空"
ReqPhoneErr = "请输入正确的手机号码"
ReqGetPhoneVerifyCodeWait="获取验证码太频繁，请稍后再试"
ReqGetPhoneVerifyCodeDayLimit="今日获取短信超出上限，请明日再试"
ReqGetPhoneVerifyCodeHourLimit="一小时内获取短信超出上限，请稍后再试"
ReqParamFormatErr1 = "{{.Field1}}不符合要求"

ConfigNotInit1 = "未配置{{.Field1}}"
PlatInvalid = "无效应用"
PlatIdErr = "应用id异常"
PlatClasErr = "应用类型异常"
Success="操作成功"
SuccessAsync="提交完成"

MysqlErr = "数据库操作失败"
MysqlInsertErr = "数据库插入失败"
MysqlUpdateErr = "数据库更新失败"
MysqlSelectErr = "数据库查询失败"
MysqlDeleteErr = "数据库删除失败"
MysqlStartTransErr = "数据库开启事务失败"
MysqlCommitErr = "数据库提交事务失败"
MysqlRollbackErr = "数据库回滚事务失败"

RedisSetErr = "缓存写入失败"
RedisGetErr = "获取缓存失败"

NotFound = "未找到该信息"
NotFoundUser = "未找到该用户"
DataExist1 = "该{{.Field1}}已存在"

NotSupportPhoneArea = "暂不支持的手机号码"
NotSupportFileType =  "不支持的文件类型"
NotSupportImageType = "不支持的图片格式"


UploadImageSizeLimited1 = "图片大小不可超过{{.Field1}}"
UploadFileSizeLimited1 = "文件大小不可超过{{.Field1}}"
UploadImageTypeLimited1 = "图片格式仅支持：{{.Field1}}"
UploadFileTypeLimited1 = "文件格式仅支持：{{.Field1}}"
MergeFileChunkNotFound = "未找到要合并的文件，请重新上传"


MultipartUploadFileHashRequired = "分片上传必须提供文件sha1哈希"
MultipartUploadNotComplete = "分片上传未全部完成"

UploadFileFail = "上传文件失败"

AccountOrPassWrong = "账号或密码错误"
VerifyCodeWrong = "验证码错误"
VerifyCodeExpired = "请先获取验证码"

SocialAlreadyFriend = "已经是好友了"
SocialAlreadyBlackMe = "对方已经将你拉黑"
SocialNotAddSelf = "不能添加自己为好友"

PhoneNumber = "手机号码"
SmsTemp ="短信模版"
MessageSysConfig = "消息中心系统参数"
Data = "数据"
Image = "图片"
Id = "id"
Account = "账号"
VarPassword = "密码"
UpoladTask = "上传任务"

[HelloPerson]
hash = "sha1-5b49bfdad81fedaeefb224b0ffc2acc58b09cff5"
other = "Hola {{.Name}}"

[MyUnreadEmails]
description = "The number of unread emails I have"
hash = "sha1-6a65d17f53981a3657db1897630e9cb069053ea8"
one = "Tengo {{.PluralCount}} correo electrónico sin leer"
other = "Tengo {{.PluralCount}} correos electrónicos no leídos"

[PersonUnreadEmails]
description = "The number of unread emails a person has"
hash = "sha1-3a672fa89c5c8564bb233c907638004983792464"
one = "{{.Name}} tiene {{.UnreadEmailCount}} correo electrónico no leído"
other = "{{.Name}} tiene {{.UnreadEmailCount}} correos electrónicos no leídos"

