ErrAccountOrPassWrong = "账号或密码错误"
ErrAuth = "权限异常"
ErrAuthOperateState = "数据状态不允许操作"
ErrAuthOperateUser = "用户无操作权限"
ErrAuthPlat = "无效应用"
ErrAuthUserNotLogin = "您还未登录"
ErrConfigNotInit1 = "未配置{{.Field1}}"
ErrCopier = "内部数据格式转换失败"
ErrCreateConversation = "创建会话失败"
ErrDataBiz = "业务数据异常"
ErrDataExist1 = "该{{.Field1}}已存在"
ErrJsonDecode = "解析json失败"
ErrJsonEncode = "转换json失败"
ErrLimiterErr = "遇到了限流问题"
ErrMergeFileChunkNotFound = "未找到合并的文件分片"
ErrMongoDelete = "数据删除失败"
ErrMongoIdHex = "不合法的ID标识"
ErrMongoInsert = "数据新增失败"
ErrMongoSelect = "数据查询失败"
ErrMongoStrToId = "数据更新标识转化失败"
ErrMongoUpdate = "数据更新失败"
ErrMqPush = "MQ推送异常"
ErrMultipartUploadFileHashRequired = "分片上传必须提供文件sha1哈希"
ErrMultipartUploadNotComplete = "分片上传未全部完成"
ErrMysql = "数据库操作失败"
ErrMysqlCommit = "数据库提交事务失败"
ErrMysqlDelete = "数据库删除失败"
ErrMysqlInsert = "数据库插入失败"
ErrMysqlPrepareUpdate = "数据库更新失败"
ErrMysqlRollback = "数据库回滚失败"
ErrMysqlSave = "数据库修改失败"
ErrMysqlSelect = "数据库查询失败"
ErrMysqlStartTrans = "数据库开启事务失败"
ErrMysqlUpdate = "数据库更新失败"
ErrNotFound1 = "{{.Field1}}不存在"
ErrNotFoundUser = "未找到该用户"
ErrNotSupportFileType = "不支持的文件类型"
ErrNotSupportImageType = "不支持的图片格式"
ErrNotSupportPhoneArea = "暂不支持的手机号码"
ErrPlatClas = "应用类型异常"
ErrPlatId = "应用id异常"
ErrPlatInvalid = "无效应用"
ErrRedis = "redis异常"
ErrRedisDec = "redis 数字自减异常"
ErrRedisGet = "获取缓存失败"
ErrRedisGetUserToken = "获取缓存失败"
ErrRedisInc = "redis 数字自增异常"
ErrRedisKeyNil = "redis key不存在"
ErrRedisSet = "缓存写入失败"
ErrRedisSetUserLoginState = "redis set异常"
ErrRedisSetVerifyCode = "redis set异常"
ErrRedisSetVerifyCodeInterval = "redis set异常"
ErrReqFieldEmpty1 = "{{.Field1}}不能为空"
ErrReqFieldRequired1 = "缺少参数{{.Field1}}"
ErrReqGetPhoneVerifyCodeDayLimit = "今日获取短信超出上限，请明日再试"
ErrReqGetPhoneVerifyCodeHourLimit = "一小时内获取短信超出上限，请稍后再试"
ErrReqGetPhoneVerifyCodeWait = "获取验证码太频繁，请稍后再试"
ErrReqKeyRequired = "未提供主键"
ErrReqParam = "请求参数不正确"
ErrReqParamFormat1 = "{{.Field1}}不符合要求"
ErrReqPhone = "请输入正确的手机号码"
ErrReqRateLimit = "请求太频繁，请休息一会"
ErrReqWait = "请求太频繁"
ErrRpcMissMeta = "缺失meta信息"
ErrRpcResDecode = "RpcResDecode"
ErrRpcService = "服务暂不可用"
ErrSocialAlreadyBlackMe = "对方已把你拉黑"
ErrSocialAlreadyFriend = "已经是好友了"
ErrSocialNotAddSelf = "不能添加自己为好友"
ErrSys = "遇到了点小问题"
ErrTrdSmsSend = "TrdSmsSend"
ErrUploadFileFail = "上传文件失败"
ErrUploadFileSizeLimited1 = "文件大小不可超过{{.Field1}}"
ErrUploadFileTypeLimited1 = "文件格式仅支持：{{.Field1}}"
ErrUploadImageSizeLimited1 = "图片大小不可超过{{.Field1}}"
ErrUploadImageTypeLimited1 = "图片格式仅支持：{{.Field1}}"
ErrUserMainInfo = "系统异常：用户信息获取失败"
ErrVerifyCodeExpired = "请先获取验证码"
ErrVerifyCodeWrong = "验证码错误"
Ok = "完成"
OkAsync = "提交成功"
VarAccount = "账号"
VarData = "数据"
VarId = "id"
VarImage = "图片"
VarMessageSysConfig = "消息中心系统参数"
VarPassword = "密码"
VarPhoneNumber = "手机号码"
VarSmsTemp = "短信模版"
VarStateEm = "状态"
VarUpoladTask = "上传任务"
VarUrl = "链接地址"


