AccountOrPassWrong = "账号或密码错误"
Auth = "权限异常"
AuthOperateStateErr = "数据状态不允许操作"
AuthOperateUserErr = "用户无操作权限"
AuthPlatErr = "无效应用"
AuthUserNotLoginErr = "您还未登录"
ConfigNotInit1 = "未配置{{.Field1}}"
CopierErr = "内部数据格式转换失败"
DataBizErr = "业务数据异常"
DataExist1 = "该{{.Field1}}已存在"
MergeFileChunkNotFound = "未找到合并的文件分片"
MqPushErr = "MQ推送异常"
MultipartUploadFileHashRequired = "分片上传必须提供文件sha1哈希"
MultipartUploadNotComplete = "分片上传未全部完成"
MysqlCommitErr = "数据库提交事务失败"
MysqlDeleteErr = "数据库删除失败"
MysqlErr = "数据库操作失败"
MysqlInsertErr = "数据库插入失败"
MysqlRollbackErr = "数据库回滚失败"
MysqlSelectErr = "数据库查询失败"
MysqlStartTransErr = "数据库开启事务失败"
MysqlUpdateErr = "数据库更新失败"
NotFound1 = "{{.Field1}}不存在"
NotFoundUser = "未找到该用户"
NotSupportFileType = "不支持的文件类型"
NotSupportImageType = "不支持的图片格式"
NotSupportPhoneArea = "暂不支持的手机号码"
Ok = "完成"
OkAsync = "提交成功"
PlatClasErr = "应用类型异常"
PlatIdErr = "应用id异常"
PlatInvalid = "无效应用"
RedisDecErr = "redis 数字自减异常"
RedisErr = "redis异常"
RedisGetErr = "获取缓存失败"
RedisGetUserTokenErr = "获取缓存失败"
RedisIncErr = "redis 数字自增异常"
RedisSetErr = "缓存写入失败"
RedisSetUserLoginStateErr = "redis set异常"
RedisSetVerifyCodeErr = "redis set异常"
RedisSetVerifyCodeIntervalErr = "redis set异常"
ReqFieldEmpty1 = "{{.Field1}}不能为空"
ReqFieldRequired1 = "缺少参数{{.Field1}}"
ReqGetPhoneVerifyCodeDayLimit = "今日获取短信超出上限，请明日再试"
ReqGetPhoneVerifyCodeHourLimit = "一小时内获取短信超出上限，请稍后再试"
ReqGetPhoneVerifyCodeWait = "获取验证码太频繁，请稍后再试"
ReqKeyRequired = "未提供主键"
ReqParamErr = "请求参数不正确"
ReqParamFormatErr1 = "{{.Field1}}不符合要求"
ReqPhoneErr = "请输入正确的手机号码"
ReqWait = "请求太频繁"
RpcResDecodeErr = "RpcResDecodeErr"
SocialAlreadyBlackMe = "对方已把你拉黑"
SocialAlreadyFriend = "已经是好友了"
SocialNotAddSelf = "不能添加自己为好友"
SysErr = "遇到了点小问题"
TrdSmsSendErr = "TrdSmsSendErr"
UploadFileFail = "上传文件失败"
UploadFileSizeLimited1 = "文件大小不可超过{{.Field1}}"
UploadFileTypeLimited1 = "文件格式仅支持：{{.Field1}}"
UploadImageSizeLimited1 = "图片大小不可超过{{.Field1}}"
UploadImageTypeLimited1 = "图片格式仅支持：{{.Field1}}"
UserMainInfoErr = "系统异常：用户信息获取失败"
VerifyCodeExpired = "请先获取验证码"
VerifyCodeWrong = "验证码错误"
Account = "账号"
Data = "数据"
Id = "id"
Image = "图片"
MessageSysConfig = "消息中心系统参数"
PhoneNumber = "手机号码"
SmsTemp = "短信模版"
UpoladTask = "上传任务"
VarPassword = "密码"


