version: '3'
services:
  Etcd:
    container_name: etcd3
    image: bitnami/etcd:${ETCD_VERSION}
    deploy:
      replicas: 1
      restart_policy:
        condition: on-failure
    environment:
      - ALLOW_NONE_AUTHENTICATION=yes
    privileged: true
    volumes:
      - ${ETCD_DIR}/data:/bitnami/etcd/data
    ports:
      - ${ETCD_PORT}:2379
      - 2380:2380
    networks:
      - dandan_net
  redis:
    container_name: redis
    image: redis:7.0
    ports:
      - 6379:6379
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    volumes:
      # 数据文件 - data files
      - ./data/redis/data:/data:rw
    command: "redis-server --requirepass G62m50oigInC30sf  --appendonly yes"
    privileged: true
    restart: always
    networks:
      - dandan_net
  #zookeeper是kafka的依赖 - Zookeeper is the dependencies of Kafka
  zookeeper:
    container_name: zookeeper
    image: zookeeper:3.8.1
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    restart: always
    ports:
      - 2181:2181
    networks:
      - dandan_net
  prometheus:
    image: bitnami/prometheus:2.44.0
    container_name: prometheus
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    volumes:
      - ${PROMETHEUS_CONF_DIR}/prometheus.yml:/opt/bitnami/prometheus/conf/prometheus.yml
      - ${PROMETHEUS_CONF_DIR}/targets.json:/opt/bitnami/prometheus/conf/targets.json
    restart: always
    #user: root
    ports:
      - 9090:9090
    networks:
      - dandan_net

  #查看prometheus监控数据 - Grafana to view Prometheus monitoring data
  #启动后http://127.0.0.1:3001/ 进入，默认账号密码都是admin
  grafana:
    image: grafana/grafana:10.0.0
    container_name: grafana
    hostname: grafana
    #user: root
    environment:
    # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    restart: always
    volumes:
      - ./data/grafana/data:/var/lib/grafana
    ports:
      - "3001:3000"
    networks:
      - dandan_net
  jaeger:
    container_name: jaeger
    image: jaegertracing/all-in-one:1.46.0
    environment:
      - TZ=Asia/Shanghai
      - SPAN_STORAGE_TYPE=elasticsearch
      - ES_SERVER_URLS=http://elasticsearch:9200
      - LOG_LEVEL=debug
    privileged: true
    ports:
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "4317:4317"
      - "4318:4318"
      - "14250:14250"
      - "14268:14268"
      - "14269:14269"
      - "9411:9411"
    restart: always
    networks:
      - dandan_net
  elasticsearch:
    container_name: elasticsearch
    #image: elasticsearch:8.8.0
    image: elasticsearch:7.13.1
    volumes:
      - ./data/elasticsearch/data:/usr/share/elasticsearch/data
    environment:
      - TZ=Asia/Shanghai
      - discovery.type=single-node
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      #以下配置是8.x版本用的，但是jaeger连不上，放弃用7了
      #- node.name=es
      #- cluster.name=elasticsearch
      #- bootstrap.memory_lock=true
      #- xpack.security.enabled=false
      #- xpack.security.http.ssl.enabled=false
      #- xpack.security.transport.ssl.enabled=false
    privileged: true
    ports:
      - "9200:9200"
      - "9300:9300"
    restart: always
    networks:
      - dandan_net
  filebeat:
    image: elastic/filebeat:8.8.0
    container_name: filebeat
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    user: root
    restart: always
    entrypoint: "filebeat -e -strict.perms=false"  #解决配置文件权限问题 - Solving the configuration file permissions
    volumes:
      - ./conf/filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml
      # 此处需指定docker的containers目录，取决于你docker的配置 - The containers directory of docker needs to be specified here, depending on your docker configuration
      # 如snap安装的docker，则为/var/snap/docker/common/var-lib-docker/containers - Example if docker is installed by Snap /var/snap/docker/common/var-lib-docker/containers
      # - /var/snap/docker/common/var-lib-docker/containers:/var/lib/docker/containers
      #- /var/lib/docker/containers:/var/lib/docker/containers
      - /Users/yelin/go_dev/project/src/go-zero-dandan/docker/data:/var/lib/docker/containers
    networks:
      - dandan_net
    depends_on:
      - kafka
  #消费kafka中filebeat收集的数据输出到es - The data output collected by FileBeat in Kafka is output to ES
  go-stash:
    #image: kevinwan/go-stash:1.0.8 # if you "macOs intel" or "linux amd"
    image: kevinwan/go-stash:1.0.8-arm64
    container_name: go-stash
    environment:
      # 时区上海 - Time zone Shanghai (Change if needed)
      TZ: Asia/Shanghai
    #user: root
    restart: always
    volumes:
      - ./conf/go-stash:/app/etc
    networks:
      - dandan_net
    depends_on:
      - elasticsearch
      - kafka
  kibana:
    #image: kibana:8.8.0
    image: kibana:7.13.1
    container_name: kibana
    environment:
      - elasticsearch.hosts=http://elasticsearch:9200
      - TZ=Asia/Shanghai
    restart: always
    networks:
      - dandan_net
    ports:
      - "5601:5601"
    depends_on:
      - elasticsearch
  #消息队列 - Message queue
  kafka:
    container_name: kafka
    image: bitnami/kafka:3.4.0
    ports:
      - 9092:9092
    environment:
      - ALLOW_PLAINTEXT_LISTENER=yes
      - KAFKA_ADVERTISED_HOST_NAME=kafka
      - KAFKA_ZOOKEEPER_CONNECT=zookeeper:2181
      - KAFKA_AUTO_CREATE_TOPICS_ENABLE=false
      - TZ=Asia/Shanghai
    restart: always
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - dandan_net
    depends_on:
    - zookeeper
networks:
  dandan_net:
    driver: bridge
    ipam:
      config:
        - subnet: 172.20.0.0/16