// Code generated by goctl. DO NOT EDIT.
// Source: message.proto

package message

import (
	"context"

	"go-zero-dandan/app/message/rpc/types/messageRpc"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EmptyReq            = messageRpc.EmptyReq
	ResultResp          = messageRpc.ResultResp
	SendImChannelMsgReq = messageRpc.SendImChannelMsgReq
	SendPhoneReq        = messageRpc.SendPhoneReq

	Message interface {
		SendPhone(ctx context.Context, in *SendPhoneReq, opts ...grpc.CallOption) (*ResultResp, error)
		SendPhoneAsync(ctx context.Context, in *SendPhoneReq, opts ...grpc.CallOption) (*ResultResp, error)
		SendImChannelMsg(ctx context.Context, in *SendImChannelMsgReq, opts ...grpc.CallOption) (*ResultResp, error)
		SendImChannelMsgAsync(ctx context.Context, in *SendImChannelMsgReq, opts ...grpc.CallOption) (*ResultResp, error)
	}

	defaultMessage struct {
		cli zrpc.Client
	}
)

func NewMessage(cli zrpc.Client) Message {
	return &defaultMessage{
		cli: cli,
	}
}

func (m *defaultMessage) SendPhone(ctx context.Context, in *SendPhoneReq, opts ...grpc.CallOption) (*ResultResp, error) {
	client := messageRpc.NewMessageClient(m.cli.Conn())
	return client.SendPhone(ctx, in, opts...)
}

func (m *defaultMessage) SendPhoneAsync(ctx context.Context, in *SendPhoneReq, opts ...grpc.CallOption) (*ResultResp, error) {
	client := messageRpc.NewMessageClient(m.cli.Conn())
	return client.SendPhoneAsync(ctx, in, opts...)
}

func (m *defaultMessage) SendImChannelMsg(ctx context.Context, in *SendImChannelMsgReq, opts ...grpc.CallOption) (*ResultResp, error) {
	client := messageRpc.NewMessageClient(m.cli.Conn())
	return client.SendImChannelMsg(ctx, in, opts...)
}

func (m *defaultMessage) SendImChannelMsgAsync(ctx context.Context, in *SendImChannelMsgReq, opts ...grpc.CallOption) (*ResultResp, error) {
	client := messageRpc.NewMessageClient(m.cli.Conn())
	return client.SendImChannelMsgAsync(ctx, in, opts...)
}
