// Code generated by goctl. DO NOT EDIT.
package conversation

import (
	"context"

	"go-zero-dandan/app/im/api/internal/svc"
	"go-zero-dandan/app/im/api/internal/types"

	"github.com/zeromicro/go-zero/core/logx"
	"go-zero-dandan/common/resd"
	"go-zero-dandan/common/typed"
)

type UpdateConversationListLogicGen struct {
	logx.Logger
	ctx          context.Context
	svc          *svc.ServiceContext
	resd         *resd.Resp
	meta         *typed.ReqMeta
	hasUserInfo  bool
	mustUserInfo bool
	req          struct {
		ConversationList map[string]*types.Conversation `json:"conversationList,optional"`
	}
	hasReq struct {
		ConversationList bool
	}
}

func NewUpdateConversationListLogicGen(ctx context.Context, svc *svc.ServiceContext) *UpdateConversationListLogicGen {
	meta, _ := ctx.Value("reqMeta").(*typed.ReqMeta)
	if meta == nil {
		meta = &typed.ReqMeta{}
	}
	return &UpdateConversationListLogicGen{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svc:    svc,
		resd:   resd.NewResp(ctx, meta.Lang),
		meta:   meta,
	}
}

func (l *UpdateConversationListLogicGen) initReq(in *types.UpdateConversationListReq) error {

	if in.ConversationList != nil {
		l.req.ConversationList = in.ConversationList
		l.hasReq.ConversationList = true
	} else {
		l.hasReq.ConversationList = false
	}

	if l.hasReq.ConversationList == false {
		return resd.NewErrWithTempCtx(l.ctx, "缺少参数ConversationList", resd.ErrReqFieldRequired1, "ConversationList")
	}
	l.hasUserInfo = true
	l.mustUserInfo = true

	return nil
}
