// Code generated by goctl. DO NOT EDIT.
package modelMongo

import (
	"context"
	"go-zero-dandan/common/resd"
	"time"

	"github.com/zeromicro/go-zero/core/stores/mon"
	"go.mongodb.org/mongo-driver/bson"
	"go.mongodb.org/mongo-driver/bson/primitive"
	"go.mongodb.org/mongo-driver/mongo"
)

type sysMsgStatModel interface {
	Insert(ctx context.Context, data *SysMsgStat) error
	FindOne(ctx context.Context, id string) (*SysMsgStat, error)
	Update(ctx context.Context, data *SysMsgStat) (*mongo.UpdateResult, error)
	Delete(ctx context.Context, id string) (int64, error)
	StartSession() (sess mongo.Session, err error)
	GetUserUnread(ctx context.Context, userId string, msgClasEm int64) ([]*SysMsgStat, error)
	IncSysMsgUnreadNum(ctx context.Context, userId string, msgClasEm int64, incNum int64) (effectedNum int64, danErr error)
	DecSysMsgUnreadNum(ctx context.Context, userId string, msgClasEm int64, decNum int64) (effectedNun int64, danErr error)
	SetZeroSysMsgUnreadNum(ctx context.Context, userId string, msgClasEm []int64) (effectedNum int64, danErr error)
}

type defaultSysMsgStatModel struct {
	conn *mon.Model
}

func newDefaultSysMsgStatModel(conn *mon.Model) *defaultSysMsgStatModel {
	return &defaultSysMsgStatModel{conn: conn}
}

func (m *defaultSysMsgStatModel) Insert(ctx context.Context, data *SysMsgStat) error {
	if data.ID.IsZero() {
		data.ID = primitive.NewObjectID()
		data.CreateAt = time.Now()
		data.UpdateAt = time.Now()
	}

	_, err := m.conn.InsertOne(ctx, data)
	if err != nil {
		return resd.ErrorCtx(ctx, err, resd.ErrMongoInsert)
	}
	return err
}

func (m *defaultSysMsgStatModel) FindOne(ctx context.Context, id string) (*SysMsgStat, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return nil, resd.ErrorCtx(ctx, err, resd.ErrMongoIdHex)
	}

	var data SysMsgStat

	err = m.conn.FindOne(ctx, &data, bson.M{"_id": oid})
	switch err {
	case nil:
		return &data, nil
	case mon.ErrNotFound:
		return nil, nil
	default:
		return nil, resd.ErrorCtx(ctx, err, resd.ErrMongoSelect)
	}
}

func (m *defaultSysMsgStatModel) Update(ctx context.Context, data *SysMsgStat) (*mongo.UpdateResult, error) {
	data.UpdateAt = time.Now()

	res, err := m.conn.UpdateOne(ctx, bson.M{"_id": data.ID}, bson.M{"$set": data})
	if err != nil {
		return nil, resd.ErrorCtx(ctx, err, resd.ErrMongoUpdate)
	}
	return res, err
}

func (m *defaultSysMsgStatModel) Delete(ctx context.Context, id string) (int64, error) {
	oid, err := primitive.ObjectIDFromHex(id)
	if err != nil {
		return 0, resd.ErrorCtx(ctx, err, resd.ErrMongoIdHex)
	}

	res, err := m.conn.DeleteOne(ctx, bson.M{"_id": oid})
	if err != nil {
		return 0, resd.ErrorCtx(ctx, err, resd.ErrMongoDelete)
	}
	return res, err
}
