// Code generated by goctl. DO NOT EDIT.
package friend

import (
	"context"

	"go-zero-dandan/app/im/api/internal/svc"
	"go-zero-dandan/app/im/api/internal/types"

	"github.com/zeromicro/go-zero/core/logx"
	"go-zero-dandan/common/resd"
	"go-zero-dandan/common/typed"
	"strings"
)

type OperateMyRecvFriendApplyLogicGen struct {
	logx.Logger
	ctx          context.Context
	svc          *svc.ServiceContext
	resd         *resd.Resp
	meta         *typed.ReqMeta
	hasUserInfo  bool
	mustUserInfo bool
	req          struct {
		ApplyId        string `json:"applyId,optional"`
		OperateStateEm int64  `json:"operateStateEm,optional"`
		OperateMsg     string `json:"operaeteMsg,optional"`
	}
	hasReq struct {
		ApplyId        bool
		OperateStateEm bool
		OperateMsg     bool
	}
}

func NewOperateMyRecvFriendApplyLogicGen(ctx context.Context, svc *svc.ServiceContext) *OperateMyRecvFriendApplyLogicGen {
	meta, _ := ctx.Value("reqMeta").(*typed.ReqMeta)
	if meta == nil {
		meta = &typed.ReqMeta{}
	}
	return &OperateMyRecvFriendApplyLogicGen{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svc:    svc,
		resd:   resd.NewResp(ctx, meta.Lang),
		meta:   meta,
	}
}

func (l *OperateMyRecvFriendApplyLogicGen) initReq(in *types.OperateMyRecvFriendApplyReq) error {

	if in.ApplyId != nil {
		l.req.ApplyId = strings.TrimSpace(*in.ApplyId)
		l.hasReq.ApplyId = true
	} else {
		l.hasReq.ApplyId = false
	}

	if l.hasReq.ApplyId == false {
		return resd.NewErrWithTempCtx(l.ctx, "缺少参数ApplyId", resd.ErrReqFieldRequired1, "ApplyId")
	}

	if l.req.ApplyId == "" {
		return resd.NewErrWithTempCtx(l.ctx, "ApplyId不得为空", resd.ErrReqFieldEmpty1, "ApplyId")
	}

	if in.OperateStateEm != nil {
		l.req.OperateStateEm = *in.OperateStateEm
		l.hasReq.OperateStateEm = true
	} else {
		l.hasReq.OperateStateEm = false
	}

	if l.hasReq.OperateStateEm == false {
		return resd.NewErrWithTempCtx(l.ctx, "缺少参数OperateStateEm", resd.ErrReqFieldRequired1, "OperateStateEm")
	}

	if in.OperateMsg != nil {
		l.req.OperateMsg = strings.TrimSpace(*in.OperateMsg)
		l.hasReq.OperateMsg = true
	} else {
		l.hasReq.OperateMsg = false
	}
	l.hasUserInfo = true
	l.mustUserInfo = true

	return nil
}
