// Code generated by goctl. DO NOT EDIT.
package sysMsg

import (
	"context"

	"go-zero-dandan/app/im/api/internal/svc"
	"go-zero-dandan/app/im/api/internal/types"

	"github.com/zeromicro/go-zero/core/logx"
	"go-zero-dandan/common/resd"
	"go-zero-dandan/common/typed"
)

type SetMySysMsgReadByClasLogicGen struct {
	logx.Logger
	ctx          context.Context
	svc          *svc.ServiceContext
	resd         *resd.Resp
	meta         *typed.ReqMeta
	hasUserInfo  bool
	mustUserInfo bool
	req          struct {
		MsgClasEms []int64 `json:"msgClasEms,optional"`
	}
	hasReq struct {
		MsgClasEms bool
	}
}

func NewSetMySysMsgReadByClasLogicGen(ctx context.Context, svc *svc.ServiceContext) *SetMySysMsgReadByClasLogicGen {
	meta, _ := ctx.Value("reqMeta").(*typed.ReqMeta)
	if meta == nil {
		meta = &typed.ReqMeta{}
	}
	return &SetMySysMsgReadByClasLogicGen{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svc:    svc,
		resd:   resd.NewResp(ctx, meta.Lang),
		meta:   meta,
	}
}

func (l *SetMySysMsgReadByClasLogicGen) initReq(in *types.SetMySysMsgReadByClasReq) error {

	if in.MsgClasEms != nil {
		l.req.MsgClasEms = in.MsgClasEms
		l.hasReq.MsgClasEms = true
	} else {
		l.hasReq.MsgClasEms = false
	}

	if l.hasReq.MsgClasEms == false {
		return resd.NewErrWithTempCtx(l.ctx, "缺少参数MsgClasEms", resd.ErrReqFieldRequired1, "MsgClasEms")
	}
	l.hasUserInfo = true
	l.mustUserInfo = true

	return nil
}
