// Code generated by goctl. DO NOT EDIT.
package types

type FriendInfo struct {
	Id              string `json:"id"`
	UserId          string `json:"userId"`
	Remark          string `json:"remark"`
	SourceEm        int64  `json:"sourceEm"`
	FriendId        string `json:"friendId"`
	FriendName      string `json:"friendName"`
	FriendAvatarImg string `json:"friendAvatarImg"`
	FriendAlias     string `json:"friendAlias"`
	PlatId          string `json:"platId"`
}

type FriendListResp struct {
	List []*FriendInfo `json:"list"`
}

type IdReq struct {
	Id     *string `json:"id,optional"`
	PlatId *string `json:"platId,optional"`
}
