// Code generated by goctl. DO NOT EDIT.
package logic

import (
	"context"
	"go-zero-dandan/app/plat/rpc/internal/svc"
	"go-zero-dandan/app/plat/rpc/types/platRpc"
	"go-zero-dandan/common/resd"
	"go-zero-dandan/common/typed"

	"github.com/zeromicro/go-zero/core/logx"
)

type GetOneLogicGen struct {
	ctx  context.Context
	svc  *svc.ServiceContext
	resd *resd.Resp
	meta *typed.ReqMeta
	logx.Logger
	req struct {
		Id string `json:"id" check:"required"`
	}
	hasReq struct {
		Id bool
	}
}

func NewGetOneLogicGen(ctx context.Context, svc *svc.ServiceContext) *GetOneLogicGen {
	meta, _ := ctx.Value("reqMeta").(*typed.ReqMeta)
	if meta == nil {
		meta = &typed.ReqMeta{}
	}
	return &GetOneLogicGen{
		ctx:    ctx,
		svc:    svc,
		Logger: logx.WithContext(ctx),
		resd:   resd.NewResp(ctx, meta.Lang),
		meta:   meta,
	}
}

func (l *GetOneLogicGen) initReq(in *platRpc.IdReq) error {

	if in.Id != nil {
		l.req.Id = *in.Id
		l.hasReq.Id = true
	} else {
		l.hasReq.Id = false
	}

	if l.hasReq.Id == false {
		return l.resd.NewErrWithTemp(resd.ErrReqFieldRequired1, "Id")
	}

	if l.req.Id == "" {
		return l.resd.NewErrWithTemp(resd.ErrReqFieldEmpty1, "Id")
	}

	return nil
}
