// Code generated by goctl. DO NOT EDIT.
package types

type UploadResp struct {
	Url      string `json:"url"`
	FileName string `json:"fileName"`
}

type UploadImgReq struct {
	WatermarkFlag int64 `form:"watermarkFlag"`
}

type DownloadReq struct {
	Id string `form:"id"`
}

type DownloadResp struct {
	Content  []byte `json:"content"`
	FileName string `json:"fileName"`
}

type SuccessResp struct {
	Msg string `json:"msg"`
}

type MultipartUploadInitReq struct {
	FileName string `json:"fileName"`
	FileSha1 string `json:"fileSha1"`
	FileSize int64  `json:"fileSize"`
}

type MultipartUploadInitRes struct {
	UserId        string  `json:"userId,omitempty"`
	State         int64   `json:"state"`
	FileSha1      string  `json:"fileSha1"`
	FileSize      int64   `json:"fileSize"`
	UploadId      string  `json:"uploadId,omitempty"`
	ChunkSize     int64   `json:"chunkSize"`
	ChunkCount    int64   `json:"chunkCount"`
	ChunkComplete []int64 `json:"chunkComplete"`
}

type MultipartUploadSendReq struct {
	UploadID   string `form:"uploadId"`
	ChunkIndex int64  `form:"chunkIndex"`
}

type MultipartUploadCompleteReq struct {
	FileSha1 string `json:"fileSha1"`
	UploadId string `json:"uploadId"`
}

type MultipartUploadCompleteRes struct {
	UploadId string `form:"uploadId"`
}
