// Code generated by goctl. DO NOT EDIT.
package logic

import (
	"context"
	"go-zero-dandan/app/user/rpc/internal/svc"
	"go-zero-dandan/app/user/rpc/types/userRpc"
	"go-zero-dandan/common/resd"
	"go-zero-dandan/common/typed"

	"github.com/zeromicro/go-zero/core/logx"
)

type GetUserNormalInfoLogicGen struct {
	ctx  context.Context
	svc  *svc.ServiceContext
	resd *resd.Resp
	meta *typed.ReqMeta
	logx.Logger
	req struct {
		Ids    []string
		PlatId string
	}
	hasReq struct {
		Ids    bool
		PlatId bool
	}
}

func NewGetUserNormalInfoLogicGen(ctx context.Context, svc *svc.ServiceContext) *GetUserNormalInfoLogicGen {
	meta, _ := ctx.Value("reqMeta").(*typed.ReqMeta)
	if meta == nil {
		meta = &typed.ReqMeta{}
	}
	return &GetUserNormalInfoLogicGen{
		ctx:    ctx,
		svc:    svc,
		Logger: logx.WithContext(ctx),
		resd:   resd.NewResp(ctx, resd.I18n.NewLang(meta.Lang)),
		meta:   meta,
	}
}

func (l *GetUserNormalInfoLogicGen) initReq(req *userRpc.GetUserInfoReq) error {

	if req.Ids != nil {
		l.req.Ids = req.Ids
		l.hasReq.Ids = true
	} else {
		l.hasReq.Ids = false
	}

	if req.PlatId != nil {
		l.req.PlatId = *req.PlatId
		l.hasReq.PlatId = true
	} else {
		l.hasReq.PlatId = false
	}

	return nil
}
