// Code generated by goctl. DO NOT EDIT.
// Source: user.proto

package user

import (
	"context"

	"go-zero-dandan/app/user/rpc/types/pb"

	"github.com/zeromicro/go-zero/zrpc"
	"google.golang.org/grpc"
)

type (
	EditUserInfoReq = pb.EditUserInfoReq
	IdReq           = pb.IdReq
	SuccResp        = pb.SuccResp
	TokenReq        = pb.TokenReq
	UserMainInfo    = pb.UserMainInfo

	User interface {
		GetUserByToken(ctx context.Context, in *TokenReq, opts ...grpc.CallOption) (*UserMainInfo, error)
		EditUserInfo(ctx context.Context, in *EditUserInfoReq, opts ...grpc.CallOption) (*SuccResp, error)
	}

	defaultUser struct {
		cli zrpc.Client
	}
)

func NewUser(cli zrpc.Client) User {
	return &defaultUser{
		cli: cli,
	}
}

func (m *defaultUser) GetUserByToken(ctx context.Context, in *TokenReq, opts ...grpc.CallOption) (*UserMainInfo, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.GetUserByToken(ctx, in, opts...)
}

func (m *defaultUser) EditUserInfo(ctx context.Context, in *EditUserInfoReq, opts ...grpc.CallOption) (*SuccResp, error) {
	client := pb.NewUserClient(m.cli.Conn())
	return client.EditUserInfo(ctx, in, opts...)
}
