// Code generated by goctl. DO NOT EDIT.
package goodsInfo

import (
	"context"

	"go-zero-dandan/app/goods/api/internal/svc"
	"go-zero-dandan/app/goods/api/internal/types"

	"github.com/zeromicro/go-zero/core/logx"
	"go-zero-dandan/app/user/rpc/user"
	"go-zero-dandan/common/resd"
	"go-zero-dandan/common/utild"
)

type GetPageLogicGen struct {
	logx.Logger
	ctx          context.Context
	svc          *svc.ServiceContext
	resd         *resd.Resp
	lang         string
	userMainInfo *user.UserMainInfo
	platId       string
	platClasEm   int64
	hasUserInfo  bool
	mustUserInfo bool
	ReqPage      string `json:"page,optional"`
	ReqSize      string `json:"size,optional"`
	ReqSort      string `json:"sort,optional"`
	ReqTotalFlag int64  `json:"totalFlag,optional"`
	HasReq       struct {
		Page      bool
		Size      bool
		Sort      bool
		TotalFlag bool
	}
}

func NewGetPageLogicGen(ctx context.Context, svc *svc.ServiceContext) *GetPageLogicGen {
	lang, _ := ctx.Value("lang").(string)
	return &GetPageLogicGen{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svc:    svc,
		lang:   lang,
		resd:   resd.NewResd(ctx, resd.I18n.NewLang(lang)),
	}
}

func (l *GetPageLogicGen) initReq(req *types.GetPageReq) error {
	var err error
	if err = l.initPlat(); err != nil {
		return resd.ErrorCtx(l.ctx, err)
	}

	if req.Page != nil {
		l.ReqPage = *req.Page
		l.HasReq.Page = true
	} else {
		l.HasReq.Page = false
	}

	if req.Size != nil {
		l.ReqSize = *req.Size
		l.HasReq.Size = true
	} else {
		l.HasReq.Size = false
	}

	if req.Sort != nil {
		l.ReqSort = *req.Sort
		l.HasReq.Sort = true
	} else {
		l.HasReq.Sort = false
	}

	if req.TotalFlag != nil {
		l.ReqTotalFlag = *req.TotalFlag
		l.HasReq.TotalFlag = true
	} else {
		l.HasReq.TotalFlag = false
	}
	l.hasUserInfo = true

	return nil
}

func (l *GetPageLogicGen) initUser() (err error) {
	userMainInfo, ok := l.ctx.Value("userMainInfo").(*user.UserMainInfo)
	if !ok {
		return resd.NewErrCtx(l.ctx, "未配置userInfo中间件", resd.UserMainInfoErr)
	}
	l.userMainInfo = userMainInfo
	return nil
}

func (l *GetPageLogicGen) initPlat() (err error) {
	platClasEm := utild.AnyToInt64(l.ctx.Value("platClasEm"))
	if platClasEm == 0 {
		return resd.NewErrCtx(l.ctx, "token中未获取到platClasEm", resd.PlatClasErr)
	}
	platId, _ := l.ctx.Value("platId").(string)
	if platId == "" {
		return resd.NewErrCtx(l.ctx, "token中未获取到platId", resd.PlatIdErr)
	}
	l.platId = platId
	l.platClasEm = platClasEm
	return nil
}
