// Code generated by goctl. DO NOT EDIT.
package wxpub

import (
	"context"

	"go-zero-dandan/app/wechat/api/internal/svc"
	"go-zero-dandan/app/wechat/api/internal/types"

	"github.com/zeromicro/go-zero/core/logx"
	"go-zero-dandan/common/resd"
	"go-zero-dandan/common/typed"
	"strings"
)

type ServiceLogicGen struct {
	logx.Logger
	ctx          context.Context
	svc          *svc.ServiceContext
	resd         *resd.Resp
	meta         *typed.ReqMeta
	hasUserInfo  bool
	mustUserInfo bool
	req          struct {
		Appid string `json:"appid"`
	}
	hasReq struct {
		Appid bool
	}
}

func NewServiceLogicGen(ctx context.Context, svc *svc.ServiceContext) *ServiceLogicGen {
	meta, _ := ctx.Value("reqMeta").(*typed.ReqMeta)
	if meta == nil {
		meta = &typed.ReqMeta{}
	}
	return &ServiceLogicGen{
		Logger: logx.WithContext(ctx),
		ctx:    ctx,
		svc:    svc,
		resd:   resd.NewResp(ctx, meta.Lang),
		meta:   meta,
	}
}

func (l *ServiceLogicGen) initReq(req *types.WxpubReq) error {

	if req.Appid != nil {
		l.req.Appid = strings.TrimSpace(*req.Appid)
		l.hasReq.Appid = true
	} else {
		l.hasReq.Appid = false
	}

	return nil
}
